export type Amulets =
  | "Coral Amulet"
  | "Paua Amulet"
  | "Amber Amulet"
  | "Jade Amulet"
  | "Lapis Amulet"
  | "Gold Amulet"
  | "Agate Amulet"
  | "Citrine Amulet"
  | "Turquoise Amulet"
  | "Onyx Amulet"
  | "Marble Amulet"
  | "Blue Pearl Amulet"
  | "Unset Amulet"
  | "Seaglass Amulet"
  | "Ruby Amulet"
  | "Astrolabe Amulet"
  | "Simplex Amulet"
  | "Focused Amulet"
  | "Pearlescent Amulet"
  | "Chieftain Talisman"
  | "Gargantuan Talisman"
  | "Goliath Talisman"
  | "Rhoa Talisman"
  | "Blood Viper Talisman"
  | "Chimeral Talisman"
  | "Squid Talisman"
  | "Sand Spitter Talisman"
  | "Shield Crab Talisman"
  | "Goatman Talisman"
  | "Devourer Talisman"
  | "Plagued Arachnid Talisman"
  | "Watcher Talisman"
  | "Savage Crab Talisman"
  | "Flame Hellion Talisman"
  | "Frost Hellion Talisman"
  | "Lynx Talisman"
  | "Ape Talisman"
  | "Wolf Alpha Talisman"
  | "Magma Hound Talisman"
  | "Pitbull Talisman"
  | "Ursa Talisman"
  | "Taurus Talisman"
  | "Retch Talisman"
  | "Cobra Talisman"
  | "Carrion Queen Talisman"
  | "Scrabbler Talisman"
  | "Black Widow Talisman"
  | "Scorpion Talisman"
  | "Tiger Talisman"
  | "Vulture Talisman"
  | "Rhex Talisman"
  | "Hybrid Arachnid Talisman"
  | "Octopus Talisman"
  | "Spider Crab Talisman"
  | "Great Maw Talisman"
  | "Croaker Talisman"
  | "Craicic Talisman"
  | "Fenumal Talisman"
  | "Saqawine Talisman"
  | "Farric Talisman"
  | "Black Maw Talisman"
  | "Greatwolf Talisman"
  | (string & {})
