export type DivinationCards =
  | "House of Mirrors"
  | "The Doctor"
  | "The Fiend"
  | "Hunter's Reward"
  | "The Dragon's Heart"
  | "Mawr Blaidd"
  | "The Last One Standing"
  | "The Offering"
  | "The Ethereal"
  | "The Queen"
  | "Abandoned Wealth"
  | "The Formless Sea"
  | "The Brittle Emperor"
  | "The Immortal"
  | "The Artist"
  | "The Thaumaturgist"
  | "Wealth and Power"
  | "The Demoness"
  | "Pride Before the Fall"
  | "The Enlightened"
  | "Heterochromia"
  | "The King's Heart"
  | "Bowyer's Dream"
  | "The Hunger"
  | "The Celestial Justicar"
  | "The Road to Power"
  | "The Arena Champion"
  | "The Gladiator"
  | "The Stormcaller"
  | "Glimmer of Hope"
  | "The Tyrant"
  | "The Cursed King"
  | "The Avenger"
  | "The Scavenger"
  | "Lost Worlds"
  | "The Union"
  | "The Risk"
  | "The Trial"
  | "Scholar of the Seas"
  | "Lucky Deck"
  | "Humility"
  | "The Penitent"
  | "The Surveyor"
  | "Lysah's Respite"
  | "The Inventor"
  | "The Watcher"
  | "The Soul"
  | "The Jester"
  | "Vinia's Token"
  | "Rats"
  | "The Wrath"
  | "Hope"
  | "Treasure Hunter"
  | "The Explorer"
  | "The Body"
  | "The Encroaching Darkness"
  | "Hubris"
  | "Jack in the Box"
  | "The Traitor"
  | "Assassin's Favour"
  | "The Battle Born"
  | "Chaotic Disposition"
  | "The Void"
  | "The Dapper Prodigy"
  | "The Vast"
  | "The Dark Mage"
  | "Last Hope"
  | "The Valkyrie"
  | "The Sephirot"
  | "Time-Lost Relic"
  | "The Harvester"
  | "The Hoarder"
  | "Emperor of Purity"
  | "The Chains that Bind"
  | "The Warlord"
  | "The Wolf"
  | "The Fletcher"
  | "The Aesthete"
  | "Earth Drinker"
  | "Lantador's Lost Love"
  | "The Spark and the Flame"
  | "The Polymath"
  | "The Saint's Treasure"
  | "A Mother's Parting Gift"
  | "The Porcupine"
  | "The Standoff"
  | "The Wolven King's Bite"
  | "Merciless Armament"
  | "Lingering Remnants"
  | "Gemcutter's Promise"
  | "The Wind"
  | "The Survivalist"
  | "Atziri's Arsenal"
  | "The Pact"
  | "The Conduit"
  | "Lucky Connections"
  | "The Opulent"
  | "Dialla's Subjugation"
  | "The Cataclysm"
  | "Emperor's Luck"
  | "Grave Knowledge"
  | "Might is Right"
  | "The Wretched"
  | "The Spoiled Prince"
  | "Gift of the Gemling Queen"
  | "The One With All"
  | "The Lion"
  | "The Poet"
  | "Tranquillity"
  | "The Forsaken"
  | "The Throne"
  | "The Garish Power"
  | "The Mercenary"
  | "Hunter's Resolve"
  | "The Rabid Rhoa"
  | "Blind Venture"
  | "Boundless Realms"
  | "Three Faces in the Dark"
  | "The Wolverine"
  | "The Siren"
  | "Coveted Possession"
  | "Mitts"
  | "Birth of the Three"
  | "The Sigil"
  | "The Calling"
  | "The Lover"
  | "The Fox"
  | "The Lord in Black"
  | "Rain Tempter"
  | "The Gentleman"
  | "The Endurance"
  | "The Hermit"
  | "Prosperity"
  | "The Oath"
  | "Rain of Chaos"
  | "Dying Anguish"
  | "The Surgeon"
  | "The Lich"
  | "The King's Blade"
  | "The Lunaris Priestess"
  | "Struck by Lightning"
  | "The Gambler"
  | "The Summoner"
  | "The Coming Storm"
  | "Doedre's Madness"
  | "The Pack Leader"
  | "The Catalyst"
  | "The Scholar"
  | "Shard of Fate"
  | "Destined to Crumble"
  | "The Flora's Gift"
  | "The Incantation"
  | "The Metalsmith's Gift"
  | "Loyalty"
  | "The Sun"
  | "The Feast"
  | "The Tower"
  | "Call to the First Ones"
  | "The Drunken Aristocrat"
  | "Her Mask"
  | "The Warden"
  | "The Gemcutter"
  | "The Doppelganger"
  | "The Wolf's Shadow"
  | "Light and Truth"
  | "Death"
  | "The Web"
  | "Volatile Power"
  | "The Twins"
  | "The Visionary"
  | "Audacity"
  | "The Inoculated"
  | "Anarchy's Price"
  | "The Betrayal"
  | "Cartographer's Delight"
  | "The Scarred Meadow"
  | "The Dragon"
  | "Rebirth"
  | "The Carrion Crow"
  | "Turn the Other Cheek"
  | "Thunderous Skies"
  | "The Ruthless Ceinture"
  | "No Traces"
  | "The Realm"
  | "The Eye of the Dragon"
  | "The Blazing Fire"
  | "Left to Fate"
  | "The Insatiable"
  | "The Rusted Bard"
  | "Forbidden Power"
  | "The Breach"
  | "The Dreamer"
  | "The World Eater"
  | "The Deceiver"
  | "Blessing of God"
  | "The Witch"
  | "Immortal Resolve"
  | "The Jeweller's Boon"
  | "The Darkest Dream"
  | "The Fathomless Depths"
  | "The Undaunted"
  | "The Admirer"
  | "The Sword King's Salute"
  | "The Army of Blood"
  | "The Celestial Stone"
  | "Perfection"
  | "The Dreamland"
  | "Harmony of Souls"
  | "The Samurai's Eye"
  | "The Hale Heart"
  | "The Mayor"
  | "The Undisputed"
  | "The Rite of Elements"
  | "Three Voices"
  | "The Professor"
  | "The Beast"
  | "The Innocent"
  | "The Wilted Rose"
  | "The Endless Darkness"
  | "Beauty Through Death"
  | "The Price of Protection"
  | "Boon of the First Ones"
  | "The Twilight Moon"
  | "The Cacophony"
  | "The Sacrifice"
  | "A Dab of Ink"
  | "The Nurse"
  | "The Master Artisan"
  | "The Life Thief"
  | "The Seeker"
  | "The Mad King"
  | "Boon of Justice"
  | "Arrogance of the Vaal"
  | "Seven Years Bad Luck"
  | "The Golden Era"
  | "Dark Temptation"
  | "Alone in the Darkness"
  | "Sambodhi's Vow"
  | "The Lord of Celebration"
  | "Vanity"
  | "Imperial Legacy"
  | "Burning Blood"
  | "The Primordial"
  | "Echoes of Love"
  | "Thirst for Knowledge"
  | "Alluring Bounty"
  | "The Fool"
  | "Pride of the First Ones"
  | "The Deep Ones"
  | "The Archmage's Right Hand"
  | "Dark Dreams"
  | "Buried Treasure"
  | "Demigod's Wager"
  | "The Old Man"
  | "Nook's Crown"
  | "The Price of Loyalty"
  | "The Heroic Shot"
  | "Remembrance"
  | "More is Never Enough"
  | "Vile Power"
  | "Azyran's Reward"
  | "The Skeleton"
  | "The Demon"
  | "Akil's Prophecy"
  | "The Damned"
  | "Void of the Elements"
  | "The Deal"
  | "The Wolf's Legacy"
  | "The Mountain"
  | "Baited Expectations"
  | "Succor of the Sinless"
  | "The Escape"
  | "Deathly Designs"
  | "The Chosen"
  | "Cameria's Cut"
  | "Divine Justice"
  | "The Fishmonger"
  | "The Bones"
  | "Friendship"
  | "The Craving"
  | "Etched in Blood"
  | "Squandered Prosperity"
  | "The Strategist"
  | "The Tinkerer's Table"
  | "The Easy Stroll"
  | "The Progeny of Lunaris"
  | "The Eldritch Decay"
  | "Council of Cats"
  | "The Tumbleweed"
  | "The Hive of Knowledge"
  | "Gift of Asenath"
  | "A Note in the Wind"
  | "The Greatest Intentions"
  | "The White Knight"
  | "Prometheus' Armoury"
  | "The Sustenance"
  | "Peaceful Moments"
  | "The Awakened"
  | "A Familiar Call"
  | "The Long Con"
  | "The Gulf"
  | "The Bitter Blossom"
  | "Triskaidekaphobia"
  | "Unrequited Love"
  | "The Cache"
  | "The Academic"
  | "Brother's Stash"
  | "Unchained"
  | "The Unexpected Prize"
  | "Cursed Words"
  | "The Journalist"
  | "Fateful Meeting"
  | "Acclimatisation"
  | "Haunting Shadows"
  | "The Whiteout"
  | "Society's Remorse"
  | "Dying Light"
  | "The Astromancer"
  | "Keeper's Corruption"
  | "Reckless Ambition"
  | "Love Through Ice"
  | "Draped in Dreams"
  | "The Patient"
  | "The Long Watch"
  | "The Bear Woman"
  | "Brotherhood in Exile"
  | "Winter's Embrace"
  | "Sambodhi's Wisdom"
  | "The Enthusiasts"
  | "Broken Promises"
  | "Brush, Paint and Palette"
  | "Deadly Joy"
  | "The Adventuring Spirit"
  | "The Eternal War"
  | "Prejudice"
  | "The Shortcut"
  | "The Card Sharp"
  | "A Modest Request"
  | "Luminous Trove"
  | "The Hook"
  | "The Last Supper"
  | "A Sea of Blue"
  | "The Offspring"
  | "The Price of Prescience"
  | "The Mind's Eyes"
  | "Terrible Secret of Space"
  | "The Blessing of Moosh"
  | "Costly Curio"
  | "Lachrymal Necrosis"
  | "Dementophobia"
  | "Ambitious Obsession"
  | "Desperate Crusade"
  | "A Stone Perfected"
  | "The Rabbit's Foot"
  | "Chasing Risk"
  | "The Prince of Darkness"
  | "The Catch"
  | "Eternal Bonds"
  | "Disdain"
  | "The Scout"
  | "Guardian's Challenge"
  | "The Forgotten Treasure"
  | "The Fox in the Brambles"
  | "The Aspirant"
  | "Judging Voices"
  | "Bijoux"
  | "Silence and Frost"
  | "Misery in Darkness"
  | "The Tireless Extractor"
  | "Justified Ambition"
  | "Parasitic Passengers"
  | "Duality"
  | "The One That Got Away"
  | "The Transformation"
  | "Magnum Opus"
  | "Imperfect Memories"
  | "The Magma Crab"
  | "Altered Perception"
  | "Further Invention"
  | "The Brawny Battle Mage"
  | "A Fate Worse Than Death"
  | "The Destination"
  | "Rebirth and Renewal"
  | "The Forward Gaze"
  | "The Apothecary"
  | "Home"
  | "The Dungeon Master"
  | "From Bone to Ashes"
  | "Darker Half"
  | "Broken Truce"
  | "Doryani's Epiphany"
  | "Endless Night"
  | "The Shieldbearer"
  | "Choking Guilt"
  | "The Enforcer"
  | "The Shepherd's Sandals"
  | "Azure Rage"
  | "The Leviathan"
  | "The Price of Devotion"
  | "Astral Protection"
  | "Gemcutter's Mercy"
  | "Checkmate"
  | "Lethean Temptation"
  | "Something Dark"
  | "Man With Bear"
  | "Alivia's Grace"
  | "Auspicious Ambitions"
  | "Divine Beauty"
  | "The Wedding Gift"
  | "The Insane Cat"
  | "Ever-Changing"
  | "A Dusty Memory"
  | "The Return of the Rat"
  | "The Finishing Touch"
  | "Brother's Gift"
  | "Soul Quenched"
  | "Poisoned Faith"
  | "A Chilling Wind"
  | "Matryoshka"
  | "Fire Of Unknown Origin"
  | "The Fortunate"
  | "I See Brothers"
  | "Assassin's Gift"
  | "Eldritch Perfection"
  | "Who Asked"
  | "Father's Love"
  | "Avian Pursuit"
  | "Temperance"
  | "Lonely Warrior"
  | "Toxic Tidings"
  | "Monochrome"
  | "Underground Forest"
  | "Runic Luck"
  | "Last Stand"
  | "Damnation"
  | "When Currents Blaze"
  | "History"
  | "The Master"
  | "The Last Laugh"
  | "The Lake"
  | "One Last Score"
  | "Bound by Flame"
  | "Outfoxed"
  | "The Everlasting"
  | "Lucky Bastion"
  | "The Miracle"
  | "Apocalypse"
  | "The Slumbering Beast"
  | "The Forbidden Fruit"
  | "The Silly Boy"
  | "Reflection of the Heart"
  | "The Eye of Terror"
  | "Desecrated Virtue"
  | "The Journey"
  | "The Messenger"
  | (string & {})
