export type MapFragments =
  | "Sacrifice at Dusk"
  | "Sacrifice at Midnight"
  | "Sacrifice at Dawn"
  | "Sacrifice at Noon"
  | "Mortal Grief"
  | "Mortal Rage"
  | "Mortal Hope"
  | "Mortal Ignorance"
  | "Fragment of the Hydra"
  | "Fragment of the Phoenix"
  | "Fragment of the Minotaur"
  | "Fragment of the Chimera"
  | "Divine Vessel"
  | "Offering to the Goddess"
  | "An Audience With The King"
  | "Craicic Lure"
  | "Farric Lure"
  | "Fenumal Lure"
  | "Saqawine Lure"
  | "Timeless Karui Emblem"
  | "Timeless Maraketh Emblem"
  | "Timeless Eternal Emblem"
  | "Timeless Templar Emblem"
  | "Timeless Vaal Emblem"
  | "Fragment of Enslavement"
  | "Fragment of Eradication"
  | "Fragment of Constriction"
  | "Fragment of Purification"
  | "Fragment of Shape"
  | "Fragment of Knowledge"
  | "Fragment of Terror"
  | "Fragment of Emptiness"
  | "Simulacrum"
  | "Tribute to the Goddess"
  | "Gift to the Goddess"
  | "Dedication to the Goddess"
  | "Blood-filled Vessel"
  | "The Maven's Writ"
  | "Sacred Blossom"
  | "Al-Hezmin's Crest"
  | "Baran's Crest"
  | "Drox's Crest"
  | "Veritania's Crest"
  | "Cosmic Fragment"
  | "Decaying Fragment"
  | "Awakening Fragment"
  | "Synthesising Fragment"
  | "Reality Fragment"
  | "Devouring Fragment"
  | "Blazing Fragment"
  | "Breach Scarab of the Hive"
  | "Breach Scarab of Instability"
  | "Breach Scarab of the Marshal"
  | "Breach Scarab of the Incensed Swarm"
  | "Cartography Scarab of Escalation"
  | "Cartography Scarab of Risk"
  | "Cartography Scarab of Corruption"
  | "Cartography Scarab of the Multitude"
  | "Titanic Scarab"
  | "Titanic Scarab of Treasures"
  | "Titanic Scarab of Legend"
  | "Bestiary Scarab"
  | "Bestiary Scarab of the Herd"
  | "Bestiary Scarab of Duplicating"
  | "Influencing Scarab of the Shaper"
  | "Influencing Scarab of the Elder"
  | "Influencing Scarab of Hordes"
  | "Influencing Scarab of Interference"
  | "Sulphite Scarab"
  | "Sulphite Scarab of Fumes"
  | "Divination Scarab of The Cloister"
  | "Divination Scarab of Plenty"
  | "Divination Scarab of Pilfering"
  | "Torment Scarab"
  | "Torment Scarab of Peculiarity"
  | "Ambush Scarab"
  | "Ambush Scarab of Hidden Compartments"
  | "Ambush Scarab of Potency"
  | "Ambush Scarab of Containment"
  | "Ambush Scarab of Discernment"
  | "Expedition Scarab"
  | "Expedition Scarab of Runefinding"
  | "Expedition Scarab of Verisium Powder"
  | "Expedition Scarab of Archaeology"
  | "Legion Scarab"
  | "Legion Scarab of Officers"
  | "Legion Scarab of Treasures"
  | "Legion Scarab of Eternal Conflict"
  | "Abyss Scarab"
  | "Abyss Scarab of Multitudes"
  | "Abyss Scarab of Crystals"
  | "Anarchy Scarab"
  | "Anarchy Scarab of Gigantification"
  | "Anarchy Scarab of Partnership"
  | "Essence Scarab"
  | "Essence Scarab of Ascent"
  | "Essence Scarab of Stability"
  | "Essence Scarab of Calcification"
  | "Domination Scarab"
  | "Domination Scarab of Apparitions"
  | "Domination Scarab of Evolution"
  | "Domination Scarab of Terrors"
  | "Ritual Scarab of Selectiveness"
  | "Ritual Scarab of Wisps"
  | "Ritual Scarab of Abundance"
  | "Harvest Scarab"
  | "Harvest Scarab of Doubling"
  | "Harvest Scarab of Cornucopia"
  | "Incursion Scarab"
  | "Incursion Scarab of Invasion"
  | "Incursion Scarab of Champions"
  | "Incursion Scarab of Timelines"
  | "Betrayal Scarab"
  | "Betrayal Scarab of the Allflame"
  | "Betrayal Scarab of Reinforcements"
  | "Beyond Scarab"
  | "Beyond Scarab of Haemophilia"
  | "Beyond Scarab of Resurgence"
  | "Beyond Scarab of the Invasion"
  | "Ultimatum Scarab"
  | "Ultimatum Scarab of Bribing"
  | "Ultimatum Scarab of Dueling"
  | "Ultimatum Scarab of Catalysing"
  | "Ultimatum Scarab of Inscription"
  | "Delirium Scarab"
  | "Delirium Scarab of Mania"
  | "Delirium Scarab of Paranoia"
  | "Delirium Scarab of Neuroses"
  | "Delirium Scarab of Delusions"
  | "Blight Scarab"
  | "Blight Scarab of the Blightheart"
  | "Blight Scarab of Blooming"
  | "Scarab of Monstrous Lineage"
  | "Scarab of Adversaries"
  | "Scarab of Divinity"
  | "Scarab of Stability"
  | "Horned Scarab of Bloodlines"
  | "Horned Scarab of Nemeses"
  | "Horned Scarab of Preservation"
  | "Horned Scarab of Awakening"
  | "Horned Scarab of Tradition"
  | "Horned Scarab of Glittering"
  | "Horned Scarab of Pandemonium"
  | "Abyss Scarab of the Consort"
  | "Blight Scarab of Invigoration"
  | "Breach Scarab of Resonant Cascade"
  | "Essence Scarab of Adaptation"
  | "Torment Scarab of Possession"
  | "Scarab of Radiant Storms"
  | "Scarab of Wisps"
  | "Scarab of the Sinistral"
  | "Kalguuran Scarab"
  | "Kalguuran Scarab of Guarded Riches"
  | "Kalguuran Scarab of Refinement"
  | "Echo of Trauma"
  | "Echo of Reverence"
  | "Echo of Loneliness"
  | "Syndicate Medallion"
  | "Allflame Ember of Kulemak"
  | "Allflame Ember of Resplendence"
  | "Allflame Ember of Propagation"
  | "Allflame Ember of Flesh"
  | "Allflame Ember of the Wildwood"
  | "Allflame Ember of the Ethereal"
  | "Allflame Ember of the Gilded"
  | "Allflame Ember of Toads"
  | "Allflame Ember of K'Tash"
  | "Hivebrain Gland"
  | "Traumatic Fragment"
  | "Reverent Fragment"
  | "Lonely Fragment"
  | "Anarchy Scarab of the Exceptional"
  | "Ritual Scarab of Corpses"
  | "Kalguuran Scarab of Enriching"
  | "The Black Barya"
  | "Scarab of the Dextral"
  | "Betrayal Scarab of Unbreaking"
  | "Abyss Scarab of Descending"
  | "Expedition Scarab of Infusion"
  | "Trarthan Scarab"
  | "Trarthan Scarab of Infamy"
  | "Trarthan Scarab of Renown"
  | "Trarthan Scarab of Surprising Alliances"
  | "Mercenary Warrant"
  | "Zorath's Eye of Malevolence"
  | "Zorath's Eye of Authority"
  | "Zorath's Eye of the Inevitable"
  | "Zorath's Eye of the Endless"
  | (string & {})
