export type Maps =
  | "Engraved Ultimatum"
  | "Map (Tier 1)"
  | "Map (Tier 2)"
  | "Map (Tier 3)"
  | "Map (Tier 4)"
  | "Map (Tier 5)"
  | "Map (Tier 6)"
  | "Map (Tier 7)"
  | "Map (Tier 8)"
  | "Map (Tier 9)"
  | "Map (Tier 10)"
  | "Map (Tier 11)"
  | "Map (Tier 12)"
  | "Map (Tier 13)"
  | "Map (Tier 14)"
  | "Map (Tier 15)"
  | "Map (Tier 16)"
  | "Valdo Map"
  | "Shaper Guardian Map"
  | "Nightmare Map"
  | "Vaal Temple Map"
  | (string & {})
