export type SkillGems =
  | "Portal"
  | "Anger"
  | "Animate Guardian"
  | "Cleave"
  | "Decoy Totem"
  | "Determination"
  | "Devouring Totem"
  | "Dominating Blow"
  | "Earthquake"
  | "Enduring Cry"
  | "Holy Flame Totem"
  | "Glacial Hammer"
  | "Ground Slam"
  | "Heavy Strike"
  | "Herald of Ash"
  | "Ice Crash"
  | "Immortal Call"
  | "Infernal Blow"
  | "Leap Slam"
  | "Molten Shell"
  | "Molten Strike"
  | "Punishment"
  | "Purity of Fire"
  | "Rallying Cry"
  | "Swordstorm"
  | "Rejuvenation Totem"
  | "Searing Bond"
  | "Shield Charge"
  | "Shockwave Totem"
  | "Static Strike"
  | "Summon Flame Golem"
  | "Summon Stone Golem"
  | "Sunder"
  | "Holy Sweep"
  | "Crushing Fist"
  | "Vigilant Strike"
  | "Vitality"
  | "Warlord's Mark"
  | "Animate Weapon"
  | "Arctic Armour"
  | "Barrage"
  | "Bear Trap"
  | "Blade Flurry"
  | "Blade Vortex"
  | "Bladefall"
  | "Blast Rain"
  | "Blink Arrow"
  | "Blood Rage"
  | "Burning Arrow"
  | "Caustic Arrow"
  | "Cyclone"
  | "Desecrate"
  | "Detonate Dead"
  | "Double Strike"
  | "Dual Strike"
  | "Elemental Hit"
  | "Ethereal Knives"
  | "Explosive Arrow"
  | "Fire Trap"
  | "Flicker Strike"
  | "Frenzy"
  | "Frost Blades"
  | "Grace"
  | "Haste"
  | "Hatred"
  | "Herald of Ice"
  | "Ice Shot"
  | "Ice Trap"
  | "Lacerate"
  | "Lightning Arrow"
  | "Lightning Strike"
  | "Mirror Arrow"
  | "Phase Run"
  | "Poacher's Mark"
  | "Sniper's Mark"
  | "Puncture"
  | "Purity of Ice"
  | "Rain of Arrows"
  | "Reave"
  | "Glacial Shield Swipe"
  | "Galvanic Arrow"
  | "Siege Ballista"
  | "Smoke Mine"
  | "Spectral Shield Throw"
  | "Spectral Throw"
  | "Split Arrow"
  | "Summon Ice Golem"
  | "Tectonic Slam"
  | "Temporal Chains"
  | "Tornado Shot"
  | "Viper Strike"
  | "Whirling Blades"
  | "Wild Strike"
  | "Arc"
  | "Assassin's Mark"
  | "Ball Lightning"
  | "Blight"
  | "Bodyswap"
  | "Bone Offering"
  | "Charged Dash"
  | "Clarity"
  | "Cold Snap"
  | "Conductivity"
  | "Contagion"
  | "Conversion Trap"
  | "Convocation"
  | "Cremation"
  | "Dark Bargain"
  | "Despair"
  | "Detonate Mines"
  | "Discharge"
  | "Discipline"
  | "Elemental Weakness"
  | "Enfeeble"
  | "Essence Drain"
  | "Fireball"
  | "Firestorm"
  | "Flame Dash"
  | "Flame Surge"
  | "Flameblast"
  | "Flammability"
  | "Flesh Offering"
  | "Freezing Pulse"
  | "Frost Bomb"
  | "Frost Wall"
  | "Frostbite"
  | "Frostbolt"
  | "Glacial Cascade"
  | "Herald of Thunder"
  | "Ice Nova"
  | "Ice Spear"
  | "Incinerate"
  | "Kinetic Blast"
  | "Lightning Tendrils"
  | "Lightning Trap"
  | "Lightning Warp"
  | "Rolling Magma"
  | "Orb of Storms"
  | "Power Siphon"
  | "Purity of Elements"
  | "Purity of Lightning"
  | "Raise Spectre"
  | "Raise Zombie"
  | "Righteous Fire"
  | "Scorching Ray"
  | "Shock Nova"
  | "Spark"
  | "Spirit Offering"
  | "Storm Burst"
  | "Storm Call"
  | "Summon Chaos Golem"
  | "Summon Lightning Golem"
  | "Summon Raging Spirit"
  | "Tempest Shield"
  | "Unearth"
  | "Volatile Dead"
  | "Vortex"
  | "Vulnerability"
  | "Wither"
  | "Wrath"
  | "Vaal Glacial Hammer"
  | "Vaal Ground Slam"
  | "Vaal Immortal Call"
  | "Vaal Molten Shell"
  | "Vaal Burning Arrow"
  | "Vaal Cyclone"
  | "Vaal Detonate Dead"
  | "Vaal Double Strike"
  | "Vaal Grace"
  | "Vaal Haste"
  | "Vaal Lightning Strike"
  | "Vaal Rain of Arrows"
  | "Vaal Reave"
  | "Vaal Spectral Throw"
  | "Vaal Arc"
  | "Vaal Clarity"
  | "Vaal Cold Snap"
  | "Vaal Discipline"
  | "Vaal Fireball"
  | "Vaal Flameblast"
  | "Vaal Ice Nova"
  | "Vaal Lightning Trap"
  | "Vaal Lightning Warp"
  | "Vaal Power Siphon"
  | "Vaal Righteous Fire"
  | "Vaal Spark"
  | "Vaal Storm Call"
  | "Vaal Summon Skeletons"
  | "Vaal Breach"
  | "Vaal Impurity of Fire"
  | "Vaal Impurity of Ice"
  | "Vaal Impurity of Lightning"
  | "Vaal Blade Vortex"
  | "Vaal Earthquake"
  | "Vaal Blight"
  | "Explosive Trap"
  | "Siphoning Trap"
  | "Flamethrower Trap"
  | "Lightning Spire Trap"
  | "Seismic Trap"
  | "Herald of Agony"
  | "Herald of Purity"
  | "Consecrated Path"
  | "Smite"
  | "Scourge Arrow"
  | "Toxic Rain"
  | "Summon Holy Relic"
  | "Winter Orb"
  | "Lancing Steel"
  | "Storm Brand"
  | "War Banner"
  | "Dread Banner"
  | "Shattering Steel"
  | "Armageddon Brand"
  | "Brand Recall"
  | "Purifying Flame"
  | "Soulrend"
  | "Bane"
  | "Divine Ire"
  | "Wave of Conviction"
  | "Zealotry"
  | "Malevolence"
  | "Steelskin"
  | "Dash"
  | "Bladestorm"
  | "Blood and Sand"
  | "Berserk"
  | "Chain Hook"
  | "Perforate"
  | "Frostblink"
  | "Precision"
  | "Flesh and Stone"
  | "Pride"
  | "Cobra Lash"
  | "Summon Carrion Golem"
  | "Withering Step"
  | "Plague Bearer"
  | "Stormblast Mine"
  | "Summon Skitterbots"
  | "Pestilent Strike"
  | "Venom Gyre"
  | "Pyroclast Mine"
  | "Icicle Mine"
  | "Summon Skeletons"
  | "Shrapnel Ballista"
  | "Ensnaring Arrow"
  | "Artillery Ballista"
  | "Stormbind"
  | "Spellslinger"
  | "Arcane Cloak"
  | "Kinetic Bolt"
  | "Blade Blast"
  | "Creeping Frost"
  | "Infernal Cry"
  | "Seismic Cry"
  | "General's Cry"
  | "Intimidating Cry"
  | "Ancestral Cry"
  | "Penance Brand"
  | "Wintertide Brand"
  | "Arcanist Brand"
  | "Earthshatter"
  | "Blazing Salvo"
  | "Void Sphere"
  | "Crackling Lance"
  | "Frost Shield"
  | "Splitting Steel"
  | "Sigil of Power"
  | "Flame Wall"
  | "Hexblast"
  | "Hydrosphere"
  | "Exsanguinate"
  | "Corrupting Fever"
  | "Reap"
  | "Petrified Blood"
  | "Defiance Banner"
  | "Voltaxic Burst"
  | "Rage Vortex"
  | "Spectral Helix"
  | "Battlemage's Cry"
  | "Absolution"
  | "Ambush"
  | "Forbidden Rite"
  | "Manabond"
  | "Blade Trap"
  | "Shield Crush"
  | "Boneshatter"
  | "Summon Reaper"
  | "Explosive Concoction"
  | "Eye of Winter"
  | "Storm Rain"
  | "Poisonous Concoction"
  | "Temporal Rift"
  | "Tornado"
  | "Energy Blade"
  | "Soul Link"
  | "Flame Link"
  | "Vampiric Link"
  | "Protective Link"
  | "Intuitive Link"
  | "Destructive Link"
  | "Lightning Conduit"
  | "Galvanic Field"
  | "Alchemist's Mark"
  | "Frozen Legion"
  | "Volcanic Fissure"
  | "Vaal Volcanic Fissure"
  | "Vaal Cleave"
  | "Vaal Flicker Strike"
  | "Vaal Blade Flurry"
  | "Vaal Venom Gyre"
  | "Vaal Molten Strike"
  | "Vaal Caustic Arrow"
  | "Vaal Smite"
  | "Vaal Firestorm"
  | "Vaal Arctic Armour"
  | "Vaal Ice Shot"
  | "Vaal Absolution"
  | "Vaal Domination"
  | "Vaal Lightning Arrow"
  | "Vaal Animate Weapon"
  | "Vaal Reap"
  | "Vaal Rejuvenation Totem"
  | "Snipe"
  | "Autoexertion"
  | "Automation"
  | "Eviscerate"
  | "Divine Retribution"
  | "Vengeful Cry"
  | "Wall of Force"
  | "Conflagration"
  | "Kinetic Rain"
  | "Kinetic Rain of Impact"
  | "Somatic Shell"
  | "Thunderstorm"
  | "Kinetic Fusillade"
  | "Dark Bargain of Trarthus"
  | "Heavy Strike of Trarthus"
  | "Spectral Shield Throw of Trarthus"
  | "Spectral Throw of Trarthus"
  | "Storm Call of Trarthus"
  | "Blast Rain of Trarthus"
  | "Siege Ballista of Trarthus"
  | "Sunder of Trarthus"
  | "Wave of Conviction of Trarthus"
  | "Chain Hook of Trarthus"
  | "Spectral Helix of Trarthus"
  | "Bladefall of Trarthus"
  | "Holy Hammers"
  | "Shield of Light"
  | "Holy Strike"
  | "Divine Blast"
  | "Charged Dash of Projection"
  | "Shock Nova of Procession"
  | "Shockwave Totem of Authority"
  | "Creeping Frost of Floes"
  | "Storm Burst of Repulsion"
  | "Static Strike of Gathering Lightning"
  | "Orb of Storms of Squalls"
  | "Siphoning Trap of Pain"
  | "Flamethrower Trap of Stability"
  | "Kinetic Fusillade of Detonation"
  | "Mana-Infused Staff"
  | "Pact of Beidat"
  | "Pact of Ghorr"
  | "Pact of K'Tash"
  | "Pact of Lycia"
  | "Holy Sweep of Hammerfalls"
  | "Reap of Butchery"
  | "Divine Blast of Radiance"
  | "Holy Hammers of Spirals"
  | (string & {})
