export type StackableCurrency =
  | "Albino Rhoa Feather"
  | "Mirror of Kalandra"
  | "Exalted Orb"
  | "Divine Orb"
  | "Chaos Orb"
  | "Vaal Orb"
  | "Regal Orb"
  | "Gemcutter's Prism"
  | "Orb of Regret"
  | "Blessed Orb"
  | "Glassblower's Bauble"
  | "Orb of Alchemy"
  | "Orb of Fusing"
  | "Orb of Scouring"
  | "Orb of Alteration"
  | "Orb of Chance"
  | "Jeweller's Orb"
  | "Chromatic Orb"
  | "Scroll of Wisdom"
  | "Portal Scroll"
  | "Armourer's Scrap"
  | "Blacksmith's Whetstone"
  | "Orb of Augmentation"
  | "Orb of Transmutation"
  | "Orb of Annulment"
  | "Orb of Binding"
  | "Ancient Orb"
  | "Annulment Shard"
  | "Chaos Shard"
  | "Mirror Shard"
  | "Exalted Shard"
  | "Regal Shard"
  | "Alchemy Shard"
  | "Transmutation Shard"
  | "Alteration Shard"
  | "Scroll Fragment"
  | "Eternal Orb"
  | "Imprint"
  | "Maven's Chisel of Procurement"
  | "Maven's Chisel of Proliferation"
  | "Maven's Chisel of Divination"
  | "Maven's Chisel of Scarabs"
  | "Maven's Chisel of Avarice"
  | "Reflecting Mist"
  | "Perandus Coin"
  | "Splinter of Xoph"
  | "Splinter of Tul"
  | "Splinter of Esh"
  | "Splinter of Uul-Netol"
  | "Splinter of Chayula"
  | "Whispering Essence of Greed"
  | "Muttering Essence of Greed"
  | "Weeping Essence of Greed"
  | "Wailing Essence of Greed"
  | "Screaming Essence of Greed"
  | "Shrieking Essence of Greed"
  | "Deafening Essence of Greed"
  | "Whispering Essence of Contempt"
  | "Muttering Essence of Contempt"
  | "Weeping Essence of Contempt"
  | "Wailing Essence of Contempt"
  | "Screaming Essence of Contempt"
  | "Shrieking Essence of Contempt"
  | "Deafening Essence of Contempt"
  | "Whispering Essence of Hatred"
  | "Muttering Essence of Hatred"
  | "Weeping Essence of Hatred"
  | "Wailing Essence of Hatred"
  | "Screaming Essence of Hatred"
  | "Shrieking Essence of Hatred"
  | "Deafening Essence of Hatred"
  | "Whispering Essence of Woe"
  | "Muttering Essence of Woe"
  | "Weeping Essence of Woe"
  | "Wailing Essence of Woe"
  | "Screaming Essence of Woe"
  | "Shrieking Essence of Woe"
  | "Deafening Essence of Woe"
  | "Muttering Essence of Fear"
  | "Weeping Essence of Fear"
  | "Wailing Essence of Fear"
  | "Screaming Essence of Fear"
  | "Shrieking Essence of Fear"
  | "Deafening Essence of Fear"
  | "Muttering Essence of Anger"
  | "Weeping Essence of Anger"
  | "Wailing Essence of Anger"
  | "Screaming Essence of Anger"
  | "Shrieking Essence of Anger"
  | "Deafening Essence of Anger"
  | "Muttering Essence of Torment"
  | "Weeping Essence of Torment"
  | "Wailing Essence of Torment"
  | "Screaming Essence of Torment"
  | "Shrieking Essence of Torment"
  | "Deafening Essence of Torment"
  | "Muttering Essence of Sorrow"
  | "Weeping Essence of Sorrow"
  | "Wailing Essence of Sorrow"
  | "Screaming Essence of Sorrow"
  | "Shrieking Essence of Sorrow"
  | "Deafening Essence of Sorrow"
  | "Weeping Essence of Rage"
  | "Wailing Essence of Rage"
  | "Screaming Essence of Rage"
  | "Shrieking Essence of Rage"
  | "Deafening Essence of Rage"
  | "Weeping Essence of Suffering"
  | "Wailing Essence of Suffering"
  | "Screaming Essence of Suffering"
  | "Shrieking Essence of Suffering"
  | "Deafening Essence of Suffering"
  | "Weeping Essence of Wrath"
  | "Wailing Essence of Wrath"
  | "Screaming Essence of Wrath"
  | "Shrieking Essence of Wrath"
  | "Deafening Essence of Wrath"
  | "Weeping Essence of Doubt"
  | "Wailing Essence of Doubt"
  | "Screaming Essence of Doubt"
  | "Shrieking Essence of Doubt"
  | "Deafening Essence of Doubt"
  | "Wailing Essence of Loathing"
  | "Screaming Essence of Loathing"
  | "Shrieking Essence of Loathing"
  | "Deafening Essence of Loathing"
  | "Wailing Essence of Zeal"
  | "Screaming Essence of Zeal"
  | "Shrieking Essence of Zeal"
  | "Deafening Essence of Zeal"
  | "Wailing Essence of Anguish"
  | "Screaming Essence of Anguish"
  | "Shrieking Essence of Anguish"
  | "Deafening Essence of Anguish"
  | "Wailing Essence of Spite"
  | "Screaming Essence of Spite"
  | "Shrieking Essence of Spite"
  | "Deafening Essence of Spite"
  | "Screaming Essence of Scorn"
  | "Shrieking Essence of Scorn"
  | "Deafening Essence of Scorn"
  | "Screaming Essence of Envy"
  | "Shrieking Essence of Envy"
  | "Deafening Essence of Envy"
  | "Screaming Essence of Misery"
  | "Shrieking Essence of Misery"
  | "Deafening Essence of Misery"
  | "Screaming Essence of Dread"
  | "Shrieking Essence of Dread"
  | "Deafening Essence of Dread"
  | "Essence of Insanity"
  | "Essence of Horror"
  | "Essence of Delirium"
  | "Essence of Hysteria"
  | "Remnant of Corruption"
  | "Stacked Deck"
  | "Unshaping Orb"
  | "Blessing of Xoph"
  | "Blessing of Tul"
  | "Blessing of Esh"
  | "Blessing of Uul-Netol"
  | "Blessing of Chayula"
  | "Imprinted Bestiary Orb"
  | "Vial of Dominance"
  | "Vial of Summoning"
  | "Vial of Awakening"
  | "Vial of the Ritual"
  | "Vial of Fate"
  | "Vial of Consequence"
  | "Vial of the Ghost"
  | "Vial of Transcendence"
  | "Vial of Sacrifice"
  | "Scorched Fossil"
  | "Frigid Fossil"
  | "Metallic Fossil"
  | "Jagged Fossil"
  | "Aberrant Fossil"
  | "Pristine Fossil"
  | "Dense Fossil"
  | "Corroded Fossil"
  | "Prismatic Fossil"
  | "Aetheric Fossil"
  | "Serrated Fossil"
  | "Lucent Fossil"
  | "Shuddering Fossil"
  | "Bound Fossil"
  | "Opulent Fossil"
  | "Faceted Fossil"
  | "Bloodstained Fossil"
  | "Hollow Fossil"
  | "Fractured Fossil"
  | "Glyphic Fossil"
  | "Tangled Fossil"
  | "Sanctified Fossil"
  | "Gilded Fossil"
  | "Timeless Karui Splinter"
  | "Timeless Maraketh Splinter"
  | "Timeless Eternal Empire Splinter"
  | "Timeless Templar Splinter"
  | "Timeless Vaal Splinter"
  | "Clear Oil"
  | "Sepia Oil"
  | "Amber Oil"
  | "Verdant Oil"
  | "Teal Oil"
  | "Azure Oil"
  | "Indigo Oil"
  | "Violet Oil"
  | "Crimson Oil"
  | "Black Oil"
  | "Opalescent Oil"
  | "Silver Oil"
  | "Golden Oil"
  | "Tainted Oil"
  | "Prismatic Oil"
  | "Turbulent Catalyst"
  | "Imbued Catalyst"
  | "Abrasive Catalyst"
  | "Tempering Catalyst"
  | "Fertile Catalyst"
  | "Prismatic Catalyst"
  | "Intrinsic Catalyst"
  | "Noxious Catalyst"
  | "Accelerating Catalyst"
  | "Unstable Catalyst"
  | "Tainted Catalyst"
  | "Crusader's Exalted Orb"
  | "Redeemer's Exalted Orb"
  | "Hunter's Exalted Orb"
  | "Warlord's Exalted Orb"
  | "Awakener's Orb"
  | "Fine Delirium Orb"
  | "Singular Delirium Orb"
  | "Thaumaturge's Delirium Orb"
  | "Blacksmith's Delirium Orb"
  | "Armoursmith's Delirium Orb"
  | "Cartographer's Delirium Orb"
  | "Jeweller's Delirium Orb"
  | "Abyssal Delirium Orb"
  | "Whispering Delirium Orb"
  | "Fragmented Delirium Orb"
  | "Skittering Delirium Orb"
  | "Fossilised Delirium Orb"
  | "Diviner's Delirium Orb"
  | "Timeless Delirium Orb"
  | "Blighted Delirium Orb"
  | "Simulacrum Splinter"
  | "Delirium Orb"
  | "Facetor's Lens"
  | "Rogue's Marker"
  | "Prime Regrading Lens"
  | "Secondary Regrading Lens"
  | "Tempering Orb"
  | "Tailoring Orb"
  | "Orb of Unmaking"
  | "Ritual Splinter"
  | "Ritual Vessel"
  | "Crescent Splinter"
  | "Enkindling Orb"
  | "Instilling Orb"
  | "Exotic Coinage"
  | "Scrap Metal"
  | "Astragali"
  | "Burial Medallion"
  | "Sacred Orb"
  | "Tainted Blessing"
  | "Tainted Chromatic Orb"
  | "Tainted Orb of Fusing"
  | "Tainted Jeweller's Orb"
  | "Deft Fossil"
  | "Fundamental Fossil"
  | "Tainted Exalted Orb"
  | "Tainted Mythic Orb"
  | "Tainted Chaos Orb"
  | "Tainted Armourer's Scrap"
  | "Tainted Divine Teardrop"
  | "Tainted Blacksmith's Whetstone"
  | "Lesser Eldritch Ember"
  | "Greater Eldritch Ember"
  | "Grand Eldritch Ember"
  | "Exceptional Eldritch Ember"
  | "Lesser Eldritch Ichor"
  | "Greater Eldritch Ichor"
  | "Grand Eldritch Ichor"
  | "Exceptional Eldritch Ichor"
  | "Orb of Conflict"
  | "Orb of Dominance"
  | "Eldritch Chaos Orb"
  | "Eldritch Exalted Orb"
  | "Eldritch Orb of Annulment"
  | "Armour Recombinator"
  | "Weapon Recombinator"
  | "Jewellery Recombinator"
  | "Reflective Oil"
  | "Wild Crystallised Lifeforce"
  | "Vivid Crystallised Lifeforce"
  | "Primal Crystallised Lifeforce"
  | "Sacred Crystallised Lifeforce"
  | "Fracturing Orb"
  | "Fracturing Shard"
  | "Lycia's Invocation of Minion Instability"
  | "Lycia's Invocation of Conduit"
  | "Lycia's Invocation of Acrobatics"
  | "Lycia's Invocation of Iron Reflexes"
  | "Lycia's Invocation of Resolute Technique"
  | "Lycia's Invocation of Unwavering Stance"
  | "Lycia's Invocation of Eldritch Battery"
  | "Lycia's Invocation of Blood Magic"
  | "Lycia's Invocation of Pain Attunement"
  | "Lycia's Invocation of Elemental Equilibrium"
  | "Lycia's Invocation of Iron Grip"
  | "Lycia's Invocation of Point Blank"
  | "Lycia's Invocation of Arrow Dancing"
  | "Lycia's Invocation of Ancestral Bond"
  | "Lycia's Invocation of Ghost Reaver"
  | "Lycia's Invocation of Vaal Pact"
  | "Lycia's Invocation of Zealot's Oath"
  | "Lycia's Invocation of Avatar of Fire"
  | "Lycia's Invocation of Mind Over Matter"
  | "Lycia's Invocation of Elemental Overload"
  | "Lycia's Invocation of Perfect Agony"
  | "Lycia's Invocation of Crimson Dance"
  | "Lycia's Invocation of Runebinder"
  | "Lycia's Invocation of Wicked Ward"
  | "Lycia's Invocation of Call to Arms"
  | "Lycia's Invocation of Eternal Youth"
  | "Lycia's Invocation of Glancing Blows"
  | "Lycia's Invocation of Wind Dancer"
  | "Lycia's Invocation of The Agnostic"
  | "Lycia's Invocation of Supreme Ego"
  | "Lycia's Invocation of Imbalanced Guard"
  | "Lycia's Invocation of The Impaler"
  | "Lycia's Invocation of Hex Master"
  | "Lycia's Invocation of Magebane"
  | "Lycia's Invocation of Iron Will"
  | "Lycia's Invocation of Solipsism"
  | "Lycia's Invocation of Ghost Dance"
  | "Lycia's Invocation of Divine Shield"
  | "Lycia's Invocation of Versatile Combatant"
  | "Lycia's Invocation of Lethe Shade"
  | "Lycia's Invocation of Precise Technique"
  | "Hinekora's Lock"
  | "Tattoo of the Ngamahu Firewalker"
  | "Tattoo of the Ngamahu Shaman"
  | "Tattoo of the Ngamahu Warrior"
  | "Tattoo of the Ngamahu Warmonger"
  | "Tattoo of the Ngamahu Woodcarver"
  | "Tattoo of the Kitava Blood Drinker"
  | "Tattoo of the Kitava Rebel"
  | "Tattoo of the Kitava Warrior"
  | "Tattoo of the Kitava Heart Eater"
  | "Tattoo of the Kitava Shaman"
  | "Tattoo of the Tukohama Shaman"
  | "Tattoo of the Tukohama Warrior"
  | "Tattoo of the Tukohama Brawler"
  | "Tattoo of the Tukohama Warmonger"
  | "Tattoo of the Tukohama Warcaller"
  | "Tattoo of the Rongokurai Warrior"
  | "Tattoo of the Rongokurai Brute"
  | "Tattoo of the Rongokurai Goliath"
  | "Tattoo of the Rongokurai Turtle"
  | "Tattoo of the Rongokurai Guard"
  | "Tattoo of the Tasalio Bladedancer"
  | "Tattoo of the Tasalio Tideshifter"
  | "Tattoo of the Tasalio Shaman"
  | "Tattoo of the Tasalio Warrior"
  | "Tattoo of the Tasalio Scout"
  | "Tattoo of the Arohongui Moonwarden"
  | "Tattoo of the Arohongui Scout"
  | "Tattoo of the Arohongui Warrior"
  | "Tattoo of the Arohongui Warmonger"
  | "Tattoo of the Arohongui Shaman"
  | "Tattoo of the Ramako Scout"
  | "Tattoo of the Ramako Archer"
  | "Tattoo of the Ramako Sniper"
  | "Tattoo of the Ramako Fleetfoot"
  | "Tattoo of the Ramako Shaman"
  | "Tattoo of the Hinekora Warrior"
  | "Tattoo of the Hinekora Deathwarden"
  | "Tattoo of the Hinekora Shaman"
  | "Tattoo of the Hinekora Storyteller"
  | "Tattoo of the Hinekora Warmonger"
  | "Tattoo of the Tawhoa Naturalist"
  | "Tattoo of the Tawhoa Scout"
  | "Tattoo of the Tawhoa Warrior"
  | "Tattoo of the Tawhoa Herbalist"
  | "Tattoo of the Tawhoa Shaman"
  | "Tattoo of the Valako Stormrider"
  | "Tattoo of the Valako Scout"
  | "Tattoo of the Valako Warrior"
  | "Tattoo of the Valako Shieldbearer"
  | "Tattoo of the Valako Shaman"
  | "Journey Tattoo of the Body"
  | "Journey Tattoo of the Mind"
  | "Journey Tattoo of the Soul"
  | "Omen of Amelioration"
  | "Omen of Return"
  | "Omen of Death-dancing"
  | "Omen of Refreshment"
  | "Omen of the Soul Devourer"
  | "Omen of Acceleration"
  | "Omen of Fortune"
  | "Omen of the Jeweller"
  | "Omen of Connections"
  | "Omen of Blanching"
  | "Omen of Revenge"
  | "Omen of Bequeathal"
  | "Omen of Resurgence"
  | "Omen of Adrenaline"
  | "Omen of Death's Door"
  | "Omen of Brilliance"
  | "Valdo's Puzzle Box"
  | "Veiled Scarab"
  | "Veiled Chaos Orb"
  | "Veiled Exalted Orb"
  | "Shaper's Exalted Orb"
  | "Elder's Exalted Orb"
  | "Orb of Remembrance"
  | "Orb of Unravelling"
  | "Orb of Intention"
  | "Runegraft of the Angler"
  | "Runegraft of the Bound"
  | "Runegraft of the Combatant"
  | "Runegraft of the Fortress"
  | "Runegraft of the Jeweller"
  | "Runegraft of the Novamark"
  | "Runegraft of the River"
  | "Runegraft of the Sinistral"
  | "Runegraft of the Soulwick"
  | "Runegraft of the Warp"
  | "Runegraft of the Witchmark"
  | "Runegraft of Bellows"
  | "Runegraft of Blasphemy"
  | "Runegraft of Gemcraft"
  | "Runegraft of Loyalty"
  | "Runegraft of Quaffing"
  | "Runegraft of Refraction"
  | "Runegraft of Restitching"
  | "Runegraft of Stability"
  | "Runegraft of Time"
  | "Runegraft of Treachery"
  | "Foulborn Orb of Augmentation"
  | "Foulborn Regal Orb"
  | "Foulborn Exalted Orb"
  | "Refracting Fog"
  | "Essence of Desolation"
  | "Flesh of Xesht"
  | "Sinistral Catalyst"
  | "Dextral Catalyst"
  | "Volatile Vaal Orb"
  | "Memory of Trauma"
  | "Memory of Reverence"
  | "Memory of Loneliness"
  | "Crystallised Rancour"
  | "Runegraft of Consecration"
  | "Runegraft of Fury"
  | "Runegraft of Rallying"
  | "Runegraft of Rotblood"
  | "Runegraft of the Imbued"
  | "Runegraft of the Agile"
  | "Runegraft of Suffering"
  | "Runegraft of the Spellbound"
  | "Runegraft of Resurgence"
  | "Runegraft of Connection"
  | "Coin of Restoration"
  | "Coin of Desecration"
  | "Coin of Knowledge"
  | "Coin of Power"
  | "Coin of Skill"
  | "Templar Astrolabe"
  | "Fruiting Astrolabe"
  | "Lightless Astrolabe"
  | "Grasping Astrolabe"
  | "Nameless Astrolabe"
  | "Fungal Astrolabe"
  | "Chaotic Astrolabe"
  | "Enshrouded Astrolabe"
  | "Timeless Astrolabe"
  | "Runic Astrolabe"
  | "Forbidden Tattoo of the Ranger"
  | "Forbidden Tattoo of the Duelist"
  | "Forbidden Tattoo of the Marauder"
  | "Forbidden Tattoo of the Templar"
  | "Forbidden Tattoo of the Witch"
  | "Forbidden Tattoo of the Shadow"
  | "Forbidden Tattoo of the Scion"
  | "Silver Coin"
  | "Loyalty Tattoo of Kaom"
  | "Tattoo of the Ngamahu Makanga"
  | "Loyalty Tattoo of Utula"
  | "Tattoo of the Kitava Makanga"
  | "Loyalty Tattoo of Akoya"
  | "Tattoo of the Tukohama Makanga"
  | "Loyalty Tattoo of Kahuturoa"
  | "Tattoo of the Rongokurai Makanga"
  | "Loyalty Tattoo of Rakiata"
  | "Tattoo of the Tasalio Makanga"
  | "Loyalty Tattoo of Ikiaho"
  | "Tattoo of the Arohongui Makanga"
  | "Loyalty Tattoo of Ahuana"
  | "Tattoo of the Ramako Makanga"
  | "Loyalty Tattoo of Tawhanuku"
  | "Tattoo of the Hinekora Makanga"
  | "Loyalty Tattoo of Maata"
  | "Tattoo of the Tawhoa Makanga"
  | "Loyalty Tattoo of Kiloava"
  | "Tattoo of the Valako Makanga"
  | "Honoured Tattoo of the Dove"
  | "Honoured Tattoo of the Sky"
  | "Honoured Tattoo of the Tuatara"
  | "Honoured Tattoo of the Pillager"
  | "Honoured Tattoo of the Turtle"
  | "Honoured Tattoo of the Oak"
  | "Honoured Tattoo of the Hatungo"
  | "Honoured Tattoo of the Flock"
  | "Honoured Tattoo of the Warlord"
  | "Honoured Tattoo of the Mountain"
  | "Honoured Tattoo of the Pa"
  | "Honoured Tattoo of the Hunter"
  | "Honoured Tattoo of the Barbarian"
  | "Honoured Tattoo of the Berserker"
  | "Honoured Tattoo of the Wise"
  | "Honoured Tattoo of the Storm"
  | "Honoured Tattoo of the Flood"
  | "Ancestral Tattoo of Bloodlines"
  | "Honoured Tattoo of the Makanga"
  | "Journey Tattoo of Makanui"
  | (string & {})
