export type SupportGems =
  | "Volley Support"
  | "Spell Cascade Support"
  | "Ancestral Call Support"
  | "Mirage Archer Support"
  | "Added Fire Damage Support"
  | "Bloodlust Support"
  | "Cast on Melee Kill Support"
  | "Cast when Damage Taken Support"
  | "Chance to Bleed Support"
  | "Cold to Fire Support"
  | "Deadly Ailments Support"
  | "Decay Support"
  | "Efficacy Support"
  | "Vile Toxins Support"
  | "Maim Support"
  | "Immolate Support"
  | "Unbound Ailments Support"
  | "Brutality Support"
  | "Ruthless Support"
  | "Arcane Surge Support"
  | "Empower Support"
  | "Endurance Charge on Melee Stun Support"
  | "Fire Penetration Support"
  | "Fortify Support"
  | "Generosity Support"
  | "Ignite Proliferation Support"
  | "Burning Damage Support"
  | "More Duration Support"
  | "Iron Grip Support"
  | "Iron Will Support"
  | "Item Quantity Support"
  | "Knockback Support"
  | "Less Duration Support"
  | "Chance to Poison Support"
  | "Life Gain on Hit Support"
  | "Life Leech Support"
  | "Damage on Full Life Support"
  | "Melee Physical Damage Support"
  | "Melee Splash Support"
  | "Multistrike Support"
  | "Spell Totem Support"
  | "Stun Support"
  | "Elemental Damage with Attacks Support"
  | "Added Cold Damage Support"
  | "Additional Accuracy Support"
  | "Blind Support"
  | "Block Chance Reduction Support"
  | "Cast On Critical Strike Support"
  | "Cast on Death Support"
  | "Chain Support"
  | "Chance to Flee Support"
  | "Cluster Traps Support"
  | "Cold Penetration Support"
  | "Culling Strike Support"
  | "Enhance Support"
  | "Faster Attacks Support"
  | "Faster Projectiles Support"
  | "Fork Support"
  | "Greater Multiple Projectiles Support"
  | "Hypothermia Support"
  | "Ice Bite Support"
  | "Multiple Projectiles Support"
  | "Mana Leech Support"
  | "Multiple Traps Support"
  | "Vicious Projectiles Support"
  | "Pierce Support"
  | "Point Blank Support"
  | "Critical Strike Affliction Support"
  | "Swift Affliction Support"
  | "Slower Projectiles Support"
  | "Advanced Traps Support"
  | "Trap Support"
  | "Trap and Mine Damage Support"
  | "Void Manipulation Support"
  | "Added Chaos Damage Support"
  | "Added Lightning Damage Support"
  | "Blasphemy Support"
  | "Cast when Stunned Support"
  | "Cast while Channelling Support"
  | "Combustion Support"
  | "Concentrated Effect Support"
  | "Controlled Destruction Support"
  | "Hextouch Support"
  | "Elemental Focus Support"
  | "Elemental Proliferation Support"
  | "Enlighten Support"
  | "Faster Casting Support"
  | "Increased Area of Effect Support"
  | "Increased Critical Damage Support"
  | "Increased Critical Strikes Support"
  | "Innervate Support"
  | "Item Rarity Support"
  | "Lightning Penetration Support"
  | "Minefield Support"
  | "Minion Damage Support"
  | "Minion Life Support"
  | "Minion Speed Support"
  | "Physical to Lightning Support"
  | "Power Charge On Critical Support"
  | "Spell Echo Support"
  | "Summon Phantasm Support"
  | "Charged Traps Support"
  | "Withering Touch Support"
  | "Multiple Totems Support"
  | "Bonechill Support"
  | "Energy Leech Support"
  | "Intensify Support"
  | "Infused Channelling Support"
  | "Unleash Support"
  | "Impale Support"
  | "Close Combat Support"
  | "Shockwave Support"
  | "Pulverise Support"
  | "Rage Support"
  | "Feeding Frenzy Support"
  | "Predator Support"
  | "Nightblade Support"
  | "Meat Shield Support"
  | "High-Impact Mine Support"
  | "Swift Assembly Support"
  | "Charged Mines Support"
  | "Infernal Legion Support"
  | "Elemental Army Support"
  | "Blastchain Mine Support"
  | "Inspiration Support"
  | "Greater Volley Support"
  | "Ballista Totem Support"
  | "Arrow Nova Support"
  | "Barrage Support"
  | "Archmage Support"
  | "Second Wind Support"
  | "Fist of War Support"
  | "Urgent Orders Support"
  | "Swiftbrand Support"
  | "Elemental Penetration Support"
  | "Pinpoint Support"
  | "Impending Doom Support"
  | "Trinity Support"
  | "Arrogance Support"
  | "Bloodthirst Support"
  | "Cruelty Support"
  | "Lifetap Support"
  | "Focused Ballista Support"
  | "Behead Support"
  | "Mark On Hit Support"
  | "Eternal Blessing Support"
  | "Overcharge Support"
  | "Hex Bloom Support"
  | "Cursed Ground Support"
  | "Momentum Support"
  | "Manaforged Arrows Support"
  | "Prismatic Burst Support"
  | "Trauma Support"
  | "Devour Support"
  | "Sadism Support"
  | "Flamewood Support"
  | "Sacrifice Support"
  | "Spellblade Support"
  | "Fresh Meat Support"
  | "Locus Mine Support"
  | "Volatility Support"
  | "Frigid Bond Support"
  | "Returning Projectiles Support"
  | "Corrupting Cry Support"
  | "Controlled Blaze Support"
  | "Guardian's Blessing Support"
  | "Sacred Wisps Support"
  | "Overexertion Support"
  | "Expert Retaliation Support"
  | "Rupture Support"
  | "Focused Channelling Support"
  | "Windburst Support"
  | "Kinetic Instability"
  | "Living Lightning Support"
  | "Kinetic Instability Support"
  | "Awakened Added Fire Damage Support"
  | "Awakened Ancestral Call Support"
  | "Awakened Brutality Support"
  | "Awakened Burning Damage Support"
  | "Awakened Elemental Damage with Attacks Support"
  | "Awakened Fire Penetration Support"
  | "Awakened Generosity Support"
  | "Awakened Melee Physical Damage Support"
  | "Awakened Melee Splash Support"
  | "Awakened Multistrike Support"
  | "Awakened Added Cold Damage Support"
  | "Awakened Arrow Nova Support"
  | "Awakened Cast On Critical Strike Support"
  | "Awakened Chain Support"
  | "Awakened Cold Penetration Support"
  | "Awakened Deadly Ailments Support"
  | "Awakened Fork Support"
  | "Awakened Greater Multiple Projectiles Support"
  | "Awakened Swift Affliction Support"
  | "Awakened Void Manipulation Support"
  | "Awakened Vicious Projectiles Support"
  | "Awakened Added Chaos Damage Support"
  | "Awakened Added Lightning Damage Support"
  | "Awakened Blasphemy Support"
  | "Awakened Cast While Channelling Support"
  | "Awakened Controlled Destruction Support"
  | "Awakened Hextouch Support"
  | "Awakened Elemental Focus Support"
  | "Awakened Increased Area of Effect Support"
  | "Awakened Lightning Penetration Support"
  | "Awakened Minion Damage Support"
  | "Awakened Spell Cascade Support"
  | "Awakened Spell Echo Support"
  | "Awakened Unbound Ailments Support"
  | "Awakened Unleash Support"
  | "Awakened Enlighten Support"
  | "Awakened Enhance Support"
  | "Awakened Empower Support"
  | "Greater Spell Cascade Support"
  | "Eclipse Support"
  | "Invert the Rules Support"
  | "Cast on Ward Break Support"
  | "Vaal Sacrifice Support"
  | "Greater Spell Echo Support"
  | "Vaal Temptation Support"
  | "Machinations Support"
  | "Pyre Support"
  | "Bonespire Support"
  | "Foulgrasp Support"
  | "Hiveborn Support"
  | "Scornful Herald Support"
  | "Cull the Weak Support"
  | "Greater Ancestral Call Support"
  | "Fissure Support"
  | "Hextoad Support"
  | "Hexpass Support"
  | "Greater Fork Support"
  | "Greater Chain Support"
  | "Lethal Dose Support"
  | "Companionship Support"
  | "Divine Sentinel Support"
  | "Annihilation Support"
  | "Invention Support"
  | "Greater Kinetic Instability Support"
  | "Cooldown Recovery Support"
  | "Voidstorm Support"
  | "Void Shockwave Support"
  | "Eldritch Blasphemy Support"
  | "Gluttony Support"
  | "Overheat Support"
  | "Greater Multistrike Support"
  | "Congregation Support"
  | "Frostmage Support"
  | "Greater Devour Support"
  | "Greater Unleash Support"
  | "Pacifism Support"
  | "Bloodsoaked Banner Support"
  | "Communion Support"
  | "Unholy Trinity Support"
  | "Overloaded Intensity Support"
  | "Transfusion Support"
  | "Excommunicate Support"
  | "Exemplar Support"
  | "Blessed Call Support"
  | "Hallow Support"
  | "Coursing Current Support"
  | "Crystalfall Support"
  | (string & {})
