import rule from "../../../rule"
import type { SoundFile } from "../../../sounds"
import type { BaseType, Color, ItemClass, Mixin, NumberRange, Operator, Rarity, Rule, Shape } from "../../../types"
import type * as Autogenerated from "../../../types/autogenerated"
import type {
  WeaponBaseType as GeneratedWeaponBaseType,
  WeaponItemClass as GeneratedWeaponItemClass,
} from "../../../types/weapon-base-data"
import { WEAPON_CLASSES as GENERATED_WEAPON_CLASSES, WEAPON_BASE_DATA } from "../../../types/weapon-base-data"
import { filterDefaults } from "../defaults"
import { filterStyles, soundFile, styleMixin } from "../styles"
import { soundFileTTS } from "../../../sounds/paths"

// Section composition helpers
export const compileRules = (...rules: Array<Rule | null | undefined | false>) => {
  const activeRules = rules.filter(Boolean) as Rule[]
  if (activeRules.length === 0) return ""
  return rule(...activeRules).compile()
}

export const joinSections = (...sections: string[]) =>
  sections
    .map((section) => section.trim())
    .filter(Boolean)
    .join("\n\n")

export const comment = (text: string, level: 1 | 2 | 3 = 1) => `${"#".repeat(level)} ${text}`

export const withHeading = (heading: string, ...sections: string[]) => joinSections(comment(heading, 3), ...sections)

export const withSubheading = (heading: string, ...sections: string[]) => joinSections(comment(heading, 1), ...sections)

// Shared item-class constants
export type DefenceBaseType = "armour" | "evasion" | "es" | "armour-evasion" | "armour-es" | "es-evasion"

export const ARMOUR_CLASSES = ["Body Armours", "Gloves", "Boots", "Helmets"] as const satisfies readonly ItemClass[]
export const SOCKETABLE_CLASSES = [...ARMOUR_CLASSES, "Shields"] as const satisfies readonly ItemClass[]
export type ArmourItemClass = (typeof ARMOUR_CLASSES)[number]
export type SocketableItemClass = (typeof SOCKETABLE_CLASSES)[number]
export type WeaponItemClass = GeneratedWeaponItemClass
export const WEAPON_CLASSES = GENERATED_WEAPON_CLASSES satisfies readonly WeaponItemClass[]
export const REMAINING_EQUIPMENT_CLASSES = [
  ...WEAPON_CLASSES,
  ...SOCKETABLE_CLASSES,
  "Amulets",
  "Belts",
  "Quivers",
  "Rings",
  "Jewels",
  "Abyss Jewels",
  "Life Flasks",
  "Mana Flasks",
  "Hybrid Flasks",
  "Utility Flasks",
  "Heist Cloaks",
  "Heist Brooches",
  "Heist Tools",
  "Heist Gear",
  "Tinctures",
  "Charms",
] as const satisfies readonly ItemClass[]

// Shared build profile and top-level section options
export type BuildProfile = {
  preferredArmourTypes: readonly DefenceBaseType[]
  preferredWeaponItemClasses?: readonly WeaponItemClass[]
  preferredWeaponMinAps?: number
  earlyWeapons?: SharedEarlyWeaponConfig
  shieldProgression?: ShieldProgressionConfig
}

export type BuildSpecificOptions = {
  links: LinksConfig
  jewellery: JewelleryConfig
  rareItems: RareItemsConfig
  magicItems: MagicItemsConfig
  normalItems: NormalItemsConfig
  tinctures: TincturesConfig
  highlightedEquipment: HighlightedEquipmentConfig
  early: EarlyConfig
}

// Links
export type SocketColorPattern = "R" | "G" | "B" | "RG" | "RB" | "GB" | "RGB"

export type LinksConfig = {
  twoLinkMaxAreaLevel?: number
  threeLinkMaxAreaLevel?: number
  fourLinkMaxAreaLevel?: number
  prefColors?: readonly SocketColorPattern[]
  twoLinkSoundId?: NumberRange<1, 17>
  threeLinkSoundId?: NumberRange<1, 17>
}

export type ShieldProgressionMode = "none" | "early" | "full"

export type ShieldProgressionConfig =
  | ShieldProgressionMode
  | {
      mode?: ShieldProgressionMode
      maxAreaLevel?: number
    }

export type NormalizedShieldProgressionConfig = {
  enabled: boolean
  maxAreaLevel?: number
}

export const normalizeSocketColorPatterns = (patterns: readonly SocketColorPattern[]) => [...new Set(patterns)]

export const normalizeShieldProgressionConfig = (shieldProgression?: ShieldProgressionConfig): NormalizedShieldProgressionConfig => {
  const defaultMode = filterDefaults.shieldProgression.mode
  const earlyMaxAreaLevel = filterDefaults.shieldProgression.earlyMaxAreaLevel

  if (typeof shieldProgression === "string" || shieldProgression === undefined) {
    const mode = shieldProgression ?? defaultMode

    if (mode === "none") {
      return { enabled: false, maxAreaLevel: earlyMaxAreaLevel }
    }

    if (mode === "full") {
      return { enabled: true, maxAreaLevel: undefined }
    }

    return { enabled: true, maxAreaLevel: earlyMaxAreaLevel }
  }

  const mode = shieldProgression.mode ?? defaultMode

  if (mode === "none") {
    return { enabled: false, maxAreaLevel: shieldProgression.maxAreaLevel ?? earlyMaxAreaLevel }
  }

  if (mode === "full") {
    return { enabled: true, maxAreaLevel: shieldProgression.maxAreaLevel }
  }

  return {
    enabled: true,
    maxAreaLevel: shieldProgression.maxAreaLevel ?? earlyMaxAreaLevel,
  }
}

export const defenceMixinMap: Record<DefenceBaseType, Mixin> = {
  "armour": (target) => target.baseArmour(">=", 1).baseES("==", 0).baseEvasion("==", 0),
  "evasion": (target) => target.baseArmour("==", 0).baseES("==", 0).baseEvasion(">=", 1),
  "es": (target) => target.baseArmour("==", 0).baseES(">=", 1).baseEvasion("==", 0),
  "armour-evasion": (target) => target.baseArmour(">=", 1).baseES("==", 0).baseEvasion(">=", 1),
  "armour-es": (target) => target.baseArmour(">=", 1).baseES(">=", 1).baseEvasion("==", 0),
  "es-evasion": (target) => target.baseArmour("==", 0).baseES(">=", 1).baseEvasion(">=", 1),
}

export const applyHighlightTargets = (
  target: Rule,
  { baseTypes, itemClasses }: { baseTypes?: readonly BaseType[]; itemClasses?: readonly ItemClass[] },
) => {
  if (baseTypes && baseTypes.length > 0) {
    target.baseType(...baseTypes)
  }

  if (itemClasses && itemClasses.length > 0) {
    target.itemClass(...itemClasses)
  }

  return target
}

const isWeaponItemClass = (itemClass: ItemClass): itemClass is WeaponItemClass => WEAPON_CLASSES.includes(itemClass as WeaponItemClass)

// Jewellery
export const LEVELING_AMULETS = {
  Amber: { baseType: "Amber Amulet", soundFileName: "amber.mp3" },
  Jade: { baseType: "Jade Amulet", soundFileName: "jade.mp3" },
  Lapis: { baseType: "Lapis Amulet", soundFileName: "lapis.mp3" },
} as const satisfies Record<string, { baseType: Autogenerated.Amulets; soundFileName: SoundFile }>

export type LevelingAmuletShortBaseType = keyof typeof LEVELING_AMULETS

export type LevelingAmuletConfig =
  | LevelingAmuletShortBaseType
  | {
      shortBaseType: LevelingAmuletShortBaseType
      soundFileName?: SoundFile
      tts?: TtsFile
    }

export type JewelleryConfig = {
  amulets?: readonly LevelingAmuletConfig[]
  amuletMaxAreaLevel?: number
  basicRingMaxAreaLevel?: number
  elementalRingMaxAreaLevel?: number
  beltMaxAreaLevel?: number
}

export const normalizeLevelingAmuletConfig = (entry: LevelingAmuletConfig) => {
  const shortBaseType = typeof entry === "string" ? entry : entry.shortBaseType
  const defaults = LEVELING_AMULETS[shortBaseType]

  return {
    baseType: defaults.baseType,
    shortBaseType,
    soundFileName: typeof entry === "string" ? defaults.soundFileName : (entry.soundFileName ?? defaults.soundFileName),
    tts: typeof entry === "string" ? undefined : entry.tts,
  }
}

export type TtsFile = string

// Highlighted equipment
export type HighlightedBaseTypeConfig = {
  baseTypes?: readonly BaseType[]
  itemClasses?: readonly ItemClass[]
  minAps?: number
  socketColors?: readonly SocketColorPattern[]
  weaponCutoffEnabled?: boolean
  weaponCutoffOverlap?: number
  rarityOperator?: Operator
  rarity?: Rarity
  rarities?: readonly Rarity[]
  minAreaLevel?: number
  maxAreaLevel?: number
  soundId?: NumberRange<1, 17>
  soundFileName?: SoundFile
  tts?: TtsFile
}

export type HighlightedEquipmentConfig = {
  highlights?: readonly HighlightedBaseTypeConfig[]
}

const highlightedEquipmentStyleMap = {
  Rare: filterStyles.highlightedEquipmentRare,
  Magic: filterStyles.highlightedEquipmentMagic,
  Normal: filterStyles.highlightedEquipmentNormal,
} as const satisfies Record<"Rare" | "Magic" | "Normal", (typeof filterStyles)[keyof typeof filterStyles]>

const HIGHLIGHTABLE_RARITIES = ["Normal", "Magic", "Rare"] as const satisfies readonly Rarity[]
type HighlightableRarity = (typeof HIGHLIGHTABLE_RARITIES)[number]
const WEAPON_BASE_INFO_MAP = new Map<WeaponBaseType, { itemClass: WeaponItemClass; dropLevel: number }>(
  WEAPON_BASE_DATA.map((weapon) => [weapon.baseType, { itemClass: weapon.itemClass, dropLevel: weapon.dropLevel }]),
)
const WEAPON_CLASS_DROP_LEVELS_MAP = new Map<WeaponItemClass, number[]>(
  WEAPON_CLASSES.map((itemClass) => [
    itemClass,
    [...new Set(WEAPON_BASE_DATA.filter((weapon) => weapon.itemClass === itemClass).map((weapon) => weapon.dropLevel))].sort(
      (left, right) => left - right,
    ),
  ]),
)

const getRaritiesForOperator = (operator: Operator, rarity: HighlightableRarity) => {
  const pivotIndex = HIGHLIGHTABLE_RARITIES.indexOf(rarity)

  switch (operator) {
    case "<":
      return HIGHLIGHTABLE_RARITIES.slice(0, pivotIndex)
    case "<=":
      return HIGHLIGHTABLE_RARITIES.slice(0, pivotIndex + 1)
    case ">":
      return HIGHLIGHTABLE_RARITIES.slice(pivotIndex + 1)
    case ">=":
      return HIGHLIGHTABLE_RARITIES.slice(pivotIndex)
    case "!=":
      return HIGHLIGHTABLE_RARITIES.filter((entry) => entry !== rarity)
    case "=":
    case "==":
    default:
      return [rarity]
  }
}

const isWeaponBaseType = (baseType: BaseType): baseType is WeaponBaseType => WEAPON_BASE_INFO_MAP.has(baseType as WeaponBaseType)

const buildHighlightedRule = ({
  selectedRarity,
  baseTypes,
  itemClasses,
  socketColor,
  minAreaLevel,
  maxAreaLevel,
  soundId,
  soundFileName,
  tts,
}: {
  selectedRarity?: Rarity
  baseTypes?: readonly BaseType[]
  itemClasses?: readonly ItemClass[]
  socketColor?: SocketColorPattern
  minAreaLevel?: number
  maxAreaLevel?: number
  soundId?: NumberRange<1, 17>
  soundFileName?: SoundFile
  tts?: TtsFile
}) => {
  const style =
    selectedRarity && selectedRarity in highlightedEquipmentStyleMap
      ? highlightedEquipmentStyleMap[selectedRarity as keyof typeof highlightedEquipmentStyleMap]
      : filterStyles.highlightedEquipment
  const builtRule = applyHighlightTargets(rule().icon("Cyan", "UpsideDownHouse").mixin(styleMixin(style)), {
    baseTypes,
    itemClasses,
  })

  if (minAreaLevel !== undefined) {
    builtRule.areaLevel(">=", minAreaLevel)
  }

  if (maxAreaLevel !== undefined) {
    builtRule.areaLevel("<=", maxAreaLevel)
  }

  if (socketColor) {
    builtRule.socketGroup(">=", socketColor)
  }

  if (tts) {
    builtRule.tts(soundFileTTS(tts))
  } else if (soundFileName) {
    builtRule.customSound(soundFile(soundFileName))
  } else if (soundId !== undefined) {
    builtRule.sound(soundId)
  }

  return builtRule
}

const getAutomaticWeaponCutoffMaxAreaLevel = (baseType: WeaponBaseType, weaponCutoffOverlap: number) => {
  const weaponBaseInfo = WEAPON_BASE_INFO_MAP.get(baseType)

  if (!weaponBaseInfo) {
    return undefined
  }

  const classDropLevels = WEAPON_CLASS_DROP_LEVELS_MAP.get(weaponBaseInfo.itemClass) ?? []
  const nextDropLevel = classDropLevels.find((dropLevel) => dropLevel > weaponBaseInfo.dropLevel)

  return nextDropLevel !== undefined ? nextDropLevel + weaponCutoffOverlap - 1 : undefined
}

export const buildHighlightedBaseTypeRules = ({
  baseTypes,
  itemClasses,
  minAps,
  socketColors,
  weaponCutoffEnabled,
  weaponCutoffOverlap = 5,
  rarityOperator,
  rarity,
  rarities,
  minAreaLevel,
  maxAreaLevel,
  soundId,
  soundFileName,
  tts,
}: HighlightedBaseTypeConfig) => {
  const appliedRarities = rarities?.length
    ? rarities.filter((entry): entry is HighlightableRarity => HIGHLIGHTABLE_RARITIES.includes(entry as HighlightableRarity))
    : rarityOperator && rarity && HIGHLIGHTABLE_RARITIES.includes(rarity as HighlightableRarity)
      ? getRaritiesForOperator(rarityOperator, rarity as HighlightableRarity)
      : [...HIGHLIGHTABLE_RARITIES]
  const weaponItemClasses = itemClasses?.filter(isWeaponItemClass)
  const nonWeaponItemClasses = itemClasses?.filter((itemClass) => !isWeaponItemClass(itemClass))
  const effectiveWeaponCutoffEnabled = weaponCutoffEnabled ?? (weaponItemClasses?.length ?? 0) > 0
  const socketPatterns = normalizeSocketColorPatterns(socketColors ?? [])
  const socketPatternVariants = socketPatterns.length > 0 ? socketPatterns : [undefined]

  if (!effectiveWeaponCutoffEnabled) {
    const { itemClasses: resolvedItemClasses, baseTypes: resolvedBaseTypes } = resolveMixedItemClassWeaponQuery({
      itemClasses,
      baseTypes,
      minAps,
    })

    return appliedRarities.flatMap((selectedRarity) =>
      socketPatternVariants.map((socketColor) =>
        buildHighlightedRule({
          selectedRarity,
          baseTypes: resolvedBaseTypes.length > 0 ? resolvedBaseTypes : undefined,
          itemClasses: resolvedItemClasses,
          socketColor,
          minAreaLevel,
          maxAreaLevel,
          soundId,
          soundFileName,
          tts,
        }).rarity("==", selectedRarity),
      ),
    )
  }

  const explicitWeaponBaseTypes = baseTypes?.filter((baseType): baseType is WeaponBaseType => isWeaponBaseType(baseType)) ?? []
  const nonWeaponBaseTypes = baseTypes?.filter((baseType) => !isWeaponBaseType(baseType)) ?? []
  const resolvedWeaponBaseTypes = resolveWeaponBaseTypes({
    itemClasses: weaponItemClasses,
    baseTypes: explicitWeaponBaseTypes,
    minAps,
  })
  const weaponRules = resolvedWeaponBaseTypes.flatMap((baseType) => {
    const automaticMaxAreaLevel = getAutomaticWeaponCutoffMaxAreaLevel(baseType, weaponCutoffOverlap)
    const effectiveMaxAreaLevel =
      maxAreaLevel !== undefined && automaticMaxAreaLevel !== undefined
        ? Math.min(maxAreaLevel, automaticMaxAreaLevel)
        : (maxAreaLevel ?? automaticMaxAreaLevel)

    return appliedRarities.flatMap((selectedRarity) =>
      socketPatternVariants.map((socketColor) =>
        buildHighlightedRule({
          selectedRarity,
          baseTypes: [baseType],
          socketColor,
          minAreaLevel,
          maxAreaLevel: effectiveMaxAreaLevel,
          soundId,
          soundFileName,
          tts,
        }).rarity("==", selectedRarity),
      ),
    )
  })
  const nonWeaponRules =
    (nonWeaponItemClasses?.length ?? 0) > 0 || nonWeaponBaseTypes.length > 0
      ? appliedRarities.flatMap((selectedRarity) =>
          socketPatternVariants.map((socketColor) =>
            buildHighlightedRule({
              selectedRarity,
              baseTypes: nonWeaponBaseTypes.length > 0 ? nonWeaponBaseTypes : undefined,
              itemClasses: nonWeaponItemClasses?.length ? nonWeaponItemClasses : undefined,
              socketColor,
              minAreaLevel,
              maxAreaLevel,
              soundId,
              soundFileName,
              tts,
            }).rarity("==", selectedRarity),
          ),
        )
      : []

  return [...weaponRules, ...nonWeaponRules]
}

// Weapon queries and early sections
export type WeaponBaseType = GeneratedWeaponBaseType

export type WeaponBaseQuery = {
  itemClasses?: readonly WeaponItemClass[]
  minAps?: number
  maxDropLevel?: number
}

export const findWeaponBaseTypes = ({ itemClasses, minAps, maxDropLevel }: WeaponBaseQuery): WeaponBaseType[] =>
  WEAPON_BASE_DATA.filter((weapon) => {
    if (itemClasses?.length && !itemClasses.includes(weapon.itemClass)) {
      return false
    }

    if (minAps !== undefined && (weapon.aps ?? 0) < minAps) {
      return false
    }

    if (maxDropLevel !== undefined && weapon.dropLevel > maxDropLevel) {
      return false
    }

    return true
  }).map((weapon) => weapon.baseType)

export const resolveWeaponBaseTypes = ({
  itemClasses = [],
  baseTypes = [],
  minAps,
}: {
  itemClasses?: readonly WeaponItemClass[]
  baseTypes?: readonly WeaponBaseType[]
  minAps?: number
}): WeaponBaseType[] => {
  const queriedBaseTypes = findWeaponBaseTypes({
    itemClasses: itemClasses.length > 0 ? itemClasses : undefined,
    minAps,
  })

  return [...new Set([...baseTypes, ...queriedBaseTypes])]
}

export const resolveMixedItemClassWeaponQuery = ({
  itemClasses,
  baseTypes = [],
  minAps,
}: {
  itemClasses?: readonly ItemClass[]
  baseTypes?: readonly BaseType[]
  minAps?: number
}) => {
  if (minAps === undefined) {
    return { itemClasses, baseTypes }
  }

  const weaponItemClasses = itemClasses?.filter(isWeaponItemClass)
  const nonWeaponItemClasses = itemClasses?.filter((itemClass) => !isWeaponItemClass(itemClass))
  const weaponBaseTypes = findWeaponBaseTypes({
    itemClasses: weaponItemClasses?.length ? weaponItemClasses : undefined,
    minAps,
  })

  return {
    itemClasses: nonWeaponItemClasses?.length ? nonWeaponItemClasses : undefined,
    baseTypes: [...new Set([...baseTypes, ...weaponBaseTypes])],
  }
}

export const resolveSharedWeaponQuery = ({
  sharedWeapons,
  preferredWeaponItemClasses = [],
  preferredWeaponMinAps,
}: {
  sharedWeapons?: SharedEarlyWeaponConfig
  preferredWeaponItemClasses?: readonly WeaponItemClass[]
  preferredWeaponMinAps?: number
}) => {
  const hasExplicitSharedWeaponTargets =
    (sharedWeapons?.itemClasses?.length ?? 0) > 0 || (sharedWeapons?.baseTypes?.length ?? 0) > 0 || sharedWeapons?.minAps !== undefined

  return hasExplicitSharedWeaponTargets
    ? {
        itemClasses: sharedWeapons?.itemClasses ?? [],
        baseTypes: sharedWeapons?.baseTypes ?? [],
        minAps: sharedWeapons?.minAps,
        maxAreaLevel: sharedWeapons?.maxAreaLevel,
      }
    : {
        itemClasses: preferredWeaponItemClasses,
        baseTypes: [],
        minAps: preferredWeaponMinAps,
        maxAreaLevel: sharedWeapons?.maxAreaLevel,
      }
}

export type SharedEarlyWeaponConfig = {
  baseTypes?: readonly WeaponBaseType[]
  itemClasses?: readonly WeaponItemClass[]
  minAps?: number
  maxAreaLevel?: number
}

export type EarlyConfig = {
  earlyMaxAreaLevel?: number
  showRustic?: boolean
}

// Rare, magic, normal items, tinctures, and chromatics
export type RareItemsConfig = {
  maxAreaLevel?: number
}

export type MagicItemsConfig = {
  maxAreaLevel?: number
}

export type NormalItemsConfig = {
  maxAreaLevel?: number
}

export type TincturesConfig = {
  baseTypes?: readonly Autogenerated.Tinctures[]
}

export type ChromaticItemsConfig = {
  smallMaxAreaLevel?: number
  largeMaxAreaLevel?: number
}

// Shared builders for section implementations
export const buildTierCurrency = (
  style: keyof typeof filterStyles,
  entries: Array<{
    baseTypes: string[]
    iconColor: Color
    iconShape: Shape
    soundId?: NumberRange<1, 17>
    soundFileName?: SoundFile
    tts?: TtsFile
  }>,
) =>
  compileRules(
    rule(
      ...entries.map(({ baseTypes, iconColor, iconShape, soundId, soundFileName, tts }) => {
        const builtRule = rule()
          .baseType(...baseTypes)
          .icon(iconColor, iconShape)

        if (tts) {
          builtRule.tts(soundFileTTS(tts))
        } else if (soundFileName) {
          builtRule.customSound(soundFile(soundFileName))
        } else if (soundId !== undefined) {
          builtRule.sound(soundId)
        }

        return builtRule
      }),
    ).mixin(styleMixin(filterStyles[style])),
  )

// Flask builders
export const buildFlaskRule = ({
  baseTypes,
  itemClass,
  rarity,
  maxAreaLevel,
  iconColor,
  sound,
  style,
}: {
  baseTypes: readonly string[]
  itemClass: "Life Flasks" | "Mana Flasks"
  rarity: "Normal" | "Magic"
  maxAreaLevel?: number
  iconColor: Color
  sound: SoundFile
  style: Mixin
}) => {
  const builtRule = rule()
    .itemClass(itemClass)
    .baseType(...baseTypes)
    .rarity("==", rarity)
    .icon(iconColor, "Raindrop")
    .mixin(style)

  if (maxAreaLevel !== undefined) {
    builtRule.areaLevel("<=", maxAreaLevel)
  }

  return builtRule.customSound(soundFile(sound))
}

export const buildFlaskSeries = ({
  itemClass,
  iconColor,
  style,
  entries,
}: {
  itemClass: "Life Flasks" | "Mana Flasks"
  iconColor: Color
  style: "lifeFlask" | "manaFlask"
  entries: Array<{ baseTypes: string[]; maxAreaLevel?: number; soundFileName: SoundFile }>
}) =>
  entries.flatMap(({ baseTypes, maxAreaLevel, soundFileName }) => [
    buildFlaskRule({
      itemClass,
      baseTypes,
      rarity: "Normal",
      maxAreaLevel,
      iconColor,
      sound: soundFileName,
      style: styleMixin(filterStyles[style]),
    }),
    buildFlaskRule({
      itemClass,
      baseTypes,
      rarity: "Magic",
      maxAreaLevel,
      iconColor,
      sound: soundFileName,
      style: styleMixin(filterStyles[style]),
    }),
  ])

export const buildUtilityFlaskRules = (entries: Array<{ baseType: string; soundFileName: SoundFile }>) =>
  entries.map(({ baseType, soundFileName }) =>
    rule()
      .itemClass("Utility Flasks")
      .baseType(baseType)
      .icon("Green", "Raindrop")
      .mixin(styleMixin(filterStyles.utilityFlask))
      .customSound(soundFile(soundFileName)),
  )
