export const LEAGUESTART_CURRENCY_BASES = [
  "Veiled Chaos Orb",
  "Exalted Shard",
  "Enkindling Orb",
  "Instilling Orb",
  "Glassblower's Bauble",
  "Gemcutter's Prism",
  "Cartographer's Chisel",
  "Annulment Shard",
  "Ancient Orb",
  "Ancient Shard",
  "Sacred Orb",
  "Chaos Shard",
  "Blessed Orb",
  "Orb of Horizons",
  "Horizon Shard",
  "Harbinger's Orb",
  "Harbinger's Shard",
  "Remnant of Corruption",
  "Alchemy Shard",
  "Singular Scouting Report",
  "Otherworldly Scouting Report",
  "Comprehensive Scouting Report",
  "Vaal Scouting Report",
  "Delirious Scouting Report",
  "Operative's Scouting Report",
  "Blighted Scouting Report",
  "Influenced Scouting Report",
  "Explorer's Scouting Report",
] as const

export const LEAGUESTART_CATALYSTS = [
  "Abrasive Catalyst",
  "Accelerating Catalyst",
  "Fertile Catalyst",
  "Imbued Catalyst",
  "Intrinsic Catalyst",
  "Noxious Catalyst",
  "Prismatic Catalyst",
  "Tainted Catalyst",
  "Tempering Catalyst",
  "Turbulent Catalyst",
  "Unstable Catalyst",
] as const

export const LEAGUESTART_FOSSILS = [
  "Aberrant Fossil",
  "Aetheric Fossil",
  "Bloodstained Fossil",
  "Bound Fossil",
  "Corroded Fossil",
  "Deft Fossil",
  "Dense Fossil",
  "Faceted Fossil",
  "Fractured Fossil",
  "Frigid Fossil",
  "Fundamental Fossil",
  "Gilded Fossil",
  "Glyphic Fossil",
  "Hollow Fossil",
  "Jagged Fossil",
  "Lucent Fossil",
  "Metallic Fossil",
  "Opulent Fossil",
  "Prismatic Fossil",
  "Pristine Fossil",
  "Sanctified Fossil",
  "Scorched Fossil",
  "Serrated Fossil",
  "Shuddering Fossil",
  "Tangled Fossil",
] as const

export const LEAGUESTART_OILS = [
  "Amber Oil",
  "Azure Oil",
  "Black Oil",
  "Clear Oil",
  "Crimson Oil",
  "Golden Oil",
  "Indigo Oil",
  "Opalescent Oil",
  "Prismatic Oil",
  "Reflective Oil",
  "Sepia Oil",
  "Silver Oil",
  "Tainted Oil",
  "Teal Oil",
  "Verdant Oil",
  "Violet Oil",
] as const

export const LEAGUESTART_SPLINTERS = [
  "Crescent Splinter",
  "Ritual Splinter",
  "Simulacrum Splinter",
  "Splinter of Chayula",
  "Splinter of Esh",
  "Splinter of Tul",
  "Splinter of Uul-Netol",
  "Splinter of Xoph",
  "Timeless Eternal Empire Splinter",
  "Timeless Karui Splinter",
  "Timeless Maraketh Splinter",
  "Timeless Templar Splinter",
  "Timeless Vaal Splinter",
] as const

export const LEAGUESTART_ELDRITCH_ICHORS = [
  "Exceptional Eldritch Ichor",
  "Grand Eldritch Ichor",
  "Greater Eldritch Ichor",
  "Lesser Eldritch Ichor",
] as const

export const LEAGUESTART_ELDRITCH_EMBERS = [
  "Exceptional Eldritch Ember",
  "Grand Eldritch Ember",
  "Greater Eldritch Ember",
  "Lesser Eldritch Ember",
] as const

export const LEAGUESTART_LIFEFORCE = [
  "Primal Crystallised Lifeforce",
  "Sacred Crystallised Lifeforce",
  "Vivid Crystallised Lifeforce",
  "Wild Crystallised Lifeforce",
] as const

export const LEAGUESTART_BLESSINGS = [
  "Blessing of Chayula",
  "Blessing of Esh",
  "Blessing of Tul",
  "Blessing of Uul-Netol",
  "Blessing of Xoph",
  "Tainted Blessing",
] as const

export const LEAGUESTART_OMENS = [
  "Omen of Acceleration",
  "Omen of Adrenaline",
  "Omen of Amelioration",
  "Omen of Bequeathal",
  "Omen of Blanching",
  "Omen of Brilliance",
  "Omen of Connections",
  "Omen of Death's Door",
  "Omen of Death-dancing",
  "Omen of Fortune",
  "Omen of Refreshment",
  "Omen of Resurgence",
  "Omen of Return",
  "Omen of Revenge",
  "Omen of the Jeweller",
  "Omen of the Soul Devourer",
] as const

export const LEAGUESTART_TATTOOS = [
  "Journey Tattoo of the Body",
  "Journey Tattoo of the Mind",
  "Journey Tattoo of the Soul",
  "Tattoo of the Arohongui Moonwarden",
  "Tattoo of the Arohongui Scout",
  "Tattoo of the Arohongui Shaman",
  "Tattoo of the Arohongui Warmonger",
  "Tattoo of the Arohongui Warrior",
  "Tattoo of the Hinekora Deathwarden",
  "Tattoo of the Hinekora Shaman",
  "Tattoo of the Hinekora Storyteller",
  "Tattoo of the Hinekora Warmonger",
  "Tattoo of the Hinekora Warrior",
  "Tattoo of the Kitava Blood Drinker",
  "Tattoo of the Kitava Heart Eater",
  "Tattoo of the Kitava Rebel",
  "Tattoo of the Kitava Shaman",
  "Tattoo of the Kitava Warrior",
  "Tattoo of the Ngamahu Firewalker",
  "Tattoo of the Ngamahu Shaman",
  "Tattoo of the Ngamahu Warmonger",
  "Tattoo of the Ngamahu Warrior",
  "Tattoo of the Ngamahu Woodcarver",
  "Tattoo of the Ramako Archer",
  "Tattoo of the Ramako Fleetfoot",
  "Tattoo of the Ramako Scout",
  "Tattoo of the Ramako Shaman",
  "Tattoo of the Ramako Sniper",
  "Tattoo of the Rongokurai Brute",
  "Tattoo of the Rongokurai Goliath",
  "Tattoo of the Rongokurai Guard",
  "Tattoo of the Rongokurai Turtle",
  "Tattoo of the Rongokurai Warrior",
  "Tattoo of the Tasalio Bladedancer",
  "Tattoo of the Tasalio Scout",
  "Tattoo of the Tasalio Shaman",
  "Tattoo of the Tasalio Tideshifter",
  "Tattoo of the Tasalio Warrior",
  "Tattoo of the Tawhoa Herbalist",
  "Tattoo of the Tawhoa Naturalist",
  "Tattoo of the Tawhoa Scout",
  "Tattoo of the Tawhoa Shaman",
  "Tattoo of the Tawhoa Warrior",
  "Tattoo of the Tukohama Brawler",
  "Tattoo of the Tukohama Shaman",
  "Tattoo of the Tukohama Warcaller",
  "Tattoo of the Tukohama Warmonger",
  "Tattoo of the Tukohama Warrior",
  "Tattoo of the Valako Scout",
  "Tattoo of the Valako Shaman",
  "Tattoo of the Valako Shieldbearer",
  "Tattoo of the Valako Stormrider",
  "Tattoo of the Valako Warrior",
] as const

export const LEAGUESTART_CURRENCY_EXACT = [
  ...LEAGUESTART_CURRENCY_BASES,
  ...LEAGUESTART_CATALYSTS,
  ...LEAGUESTART_FOSSILS,
  ...LEAGUESTART_OILS,
  ...LEAGUESTART_SPLINTERS,
  ...LEAGUESTART_ELDRITCH_ICHORS,
  ...LEAGUESTART_ELDRITCH_EMBERS,
  ...LEAGUESTART_LIFEFORCE,
  ...LEAGUESTART_BLESSINGS,
  ...LEAGUESTART_OMENS,
  ...LEAGUESTART_TATTOOS,
] as const
