import type { BaseType, Color, ItemClass, NumberRange, Operator, Rarity } from "../../../types"
import type * as Autogenerated from "../../../types/autogenerated"
import type { SoundFile } from "../../../sounds"
import { MANIFEST_BY_ID, type SoundManifestEntry } from "../../../sounds/manifest"
import { filterDefaults } from "../defaults"
import type { DefenceBaseType, SocketableItemClass, WeaponItemClass } from "./item-classes"
import type { WeaponBaseType } from "./weapon-queries"

export type SocketColorPattern = "R" | "G" | "B" | "RG" | "RB" | "GB" | "RGB"
export type TtsFile = string | SoundManifestEntry
export type ShieldProgressionMode = "none" | "early" | "full"
export type ShieldProgressionConfig = ShieldProgressionMode | { mode?: ShieldProgressionMode; maxAreaLevel?: number }
export type SharedEarlyWeaponConfig = {
  baseTypes?: readonly WeaponBaseType[]
  itemClasses?: readonly WeaponItemClass[]
  minAps?: number
  maxAreaLevel?: number
}
export type BuildProfile = {
  preferredArmourTypes?: readonly DefenceBaseType[]
  preferredWeaponItemClasses?: readonly WeaponItemClass[]
  preferredWeaponMinAps?: number
  earlyWeapons?: SharedEarlyWeaponConfig
  shieldProgression?: ShieldProgressionConfig
}
export type SocketColor = "R" | "G" | "B"
export type AnyTwoLinkPattern = `${SocketColor}${SocketColor}`
export type AnyThreeLinkPattern = `${SocketColor}${SocketColor}${SocketColor}`
export type AnyFourLinkPattern = `${SocketColor}${SocketColor}${SocketColor}${SocketColor}`
export type TwoLinkPattern = "RR" | "RG" | "RB" | "GG" | "GB" | "BB"
export type ThreeLinkPattern = "RRR" | "RRG" | "RRB" | "GGR" | "RGB" | "BBR" | "GGG" | "GGB" | "BBG" | "BBB"
export type FourLinkPattern =
  | "RRRR"
  | "RRRG"
  | "RRRB"
  | "RRGG"
  | "RRGB"
  | "RRBB"
  | "GGGR"
  | "GGRB"
  | "BBRG"
  | "BBBR"
  | "GGGG"
  | "GGGB"
  | "GGBB"
  | "BBBG"
  | "BBBB"
export type SocketPattern = TwoLinkPattern | ThreeLinkPattern | FourLinkPattern
export type SocketPatternConfig<TPattern extends string = SocketPattern> = {
  pattern: TPattern
  maxAreaLevel?: number
  itemClasses?: readonly SocketableItemClass[]
}
export type GoodFourLinkConfig = {
  defenceType: DefenceBaseType
  maxAreaLevel?: number
}
export type LinksConfig = {
  twoLinkPatterns?: readonly (AnyTwoLinkPattern | SocketPatternConfig<AnyTwoLinkPattern>)[]
  twoLinkMaxAreaLevel?: number
  threeLinkPatterns?: readonly (AnyThreeLinkPattern | SocketPatternConfig<AnyThreeLinkPattern>)[]
  threeLinkMaxAreaLevel?: number
  goodThreeLinksEnabled?: boolean
  genericThreeLinksEnabled?: boolean
  fourLinkPatterns?: readonly (AnyFourLinkPattern | SocketPatternConfig<AnyFourLinkPattern>)[]
  goodFourLinksEnabled?: boolean
  genericFourLinksEnabled?: boolean
  goodFourLinks?: readonly (DefenceBaseType | GoodFourLinkConfig)[]
}
export type JewelleryConfig = {
  amulets?: readonly LevelingAmuletConfig[]
  amuletMaxAreaLevel?: number
  basicRingMaxAreaLevel?: number
  elementalRingMaxAreaLevel?: number
  beltMaxAreaLevel?: number
}
export type RareItemsConfig = { maxAreaLevel?: number }
export type MagicItemsConfig = { maxAreaLevel?: number }
export type NormalItemsConfig = { maxAreaLevel?: number }
export type TincturesConfig = { baseTypes?: readonly Autogenerated.Tinctures[] }
export type EarlyConfig = {
  earlyMaxAreaLevel?: number
  showRustic?: boolean
  includeMomentumColors?: boolean
  momentumColors?: {
    itemClasses?: readonly ItemClass[]
    baseTypes?: readonly BaseType[]
    minAps?: number
    maxAreaLevel?: number
  }
  momentumMaxAreaLevel?: number
}
export type ChromaticItemsConfig = { smallMaxAreaLevel?: number; largeMaxAreaLevel?: number }
export type HighlightedBaseTypeConfig = {
  baseTypes?: readonly BaseType[]
  itemClasses?: readonly ItemClass[]
  minAps?: number
  socketColors?: readonly SocketColorPattern[]
  socketGroups?: readonly string[]
  socketGroupOperator?: Operator
  weaponCutoffEnabled?: boolean
  weaponCutoffOverlap?: number
  rarityOperator?: Operator
  rarity?: Rarity
  rarities?: readonly Rarity[]
  minAreaLevel?: number
  maxAreaLevel?: number
  soundId?: NumberRange<1, 17>
  soundFileName?: SoundFile
  tts?: TtsFile
  rarityIconColors?: Partial<Record<"Normal" | "Magic" | "Rare", Color>>
  raritySoundIds?: Partial<Record<"Normal" | "Magic" | "Rare", NumberRange<1, 17>>>
  legacyConditionOrder?: boolean
}
export type HighlightedEquipmentConfig = { highlights?: readonly HighlightedBaseTypeConfig[] }
export type BuildSpecificOptions = {
  links?: LinksConfig
  jewellery?: JewelleryConfig
  rareItems?: RareItemsConfig
  magicItems?: MagicItemsConfig
  normalItems?: NormalItemsConfig
  tinctures?: TincturesConfig
  highlightedEquipment?: HighlightedEquipmentConfig
  early?: EarlyConfig
}

export type NormalizedShieldProgressionConfig = {
  enabled: boolean
  maxAreaLevel?: number
}

export const getShieldProgressionMode = (shieldProgression?: ShieldProgressionConfig): ShieldProgressionMode =>
  typeof shieldProgression === "string" ? shieldProgression : (shieldProgression?.mode ?? filterDefaults.shieldProgression.mode)

export const SOCKET_COLOR_PRIORITY = { R: 0, G: 1, B: 2 } as const
export const SOCKET_EFFECT_COLOR_MAP = { R: "Red", G: "Green", B: "Blue" } as const satisfies Record<SocketColor, Color>
export const DEFENCE_TYPE_HIGHLIGHT_COLOR_MAP = {
  "armour": "Red",
  "evasion": "Green",
  "es": "Blue",
  "armour-evasion": "White",
  "armour-es": "White",
  "es-evasion": "White",
} as const satisfies Record<DefenceBaseType, Color>

export const normalizeSocketPattern = <TPattern extends SocketPattern>(pattern: string): TPattern => {
  const socketColors = [...pattern]
  if (!socketColors.every((color): color is SocketColor => color in SOCKET_COLOR_PRIORITY)) {
    throw new Error(`Invalid socket pattern "${pattern}". Only R, G, and B are allowed.`)
  }
  const colorCounts = socketColors.reduce<Record<SocketColor, number>>(
    (counts, color) => {
      counts[color] += 1
      return counts
    },
    { R: 0, G: 0, B: 0 },
  )
  return [...socketColors]
    .sort((left, right) => {
      const delta = colorCounts[right] - colorCounts[left]
      return delta !== 0 ? delta : SOCKET_COLOR_PRIORITY[left] - SOCKET_COLOR_PRIORITY[right]
    })
    .join("") as TPattern
}

export const getSocketPatternEffectColor = (pattern: string): Color => {
  const socketColors = [...pattern]
  if (!socketColors.every((color): color is SocketColor => color in SOCKET_COLOR_PRIORITY)) {
    throw new Error(`Invalid socket pattern "${pattern}". Only R, G, and B are allowed.`)
  }
  const colorCounts = socketColors.reduce<Record<SocketColor, number>>(
    (counts, color) => {
      counts[color] += 1
      return counts
    },
    { R: 0, G: 0, B: 0 },
  )
  const highest = Math.max(...Object.values(colorCounts))
  const highestColors = (Object.entries(colorCounts) as [SocketColor, number][])
    .filter(([, count]) => count === highest)
    .map(([color]) => color)
  return highestColors.length === 1 ? SOCKET_EFFECT_COLOR_MAP[highestColors[0]] : "White"
}

export const getDefenceTypeHighlightColor = (defenceType: DefenceBaseType): Color => DEFENCE_TYPE_HIGHLIGHT_COLOR_MAP[defenceType]

export const normalizeSocketPatternConfig = <TNormalized extends SocketPattern, TRaw extends string = string>(
  entry: TRaw | SocketPatternConfig<TRaw>,
): SocketPatternConfig<TNormalized> => {
  const normalized = typeof entry === "string" ? { pattern: entry } : entry
  return { ...normalized, pattern: normalizeSocketPattern<TNormalized>(normalized.pattern) }
}

export const normalizeGoodFourLinkConfig = (entry: DefenceBaseType | GoodFourLinkConfig): GoodFourLinkConfig =>
  typeof entry === "string" ? { defenceType: entry } : entry

export const LEVELING_AMULETS = {
  Amber: { baseType: "Amber Amulet", entry: MANIFEST_BY_ID.amber_amulet },
  Jade: { baseType: "Jade Amulet", entry: MANIFEST_BY_ID.jade_amulet },
  Lapis: { baseType: "Lapis Amulet", entry: MANIFEST_BY_ID.lapis_amulet },
} as const

export type LevelingAmuletShortBaseType = keyof typeof LEVELING_AMULETS
export type LevelingAmuletConfig = LevelingAmuletShortBaseType | { shortBaseType: LevelingAmuletShortBaseType }
export const normalizeLevelingAmuletConfig = (entry: LevelingAmuletConfig) => {
  const shortBaseType = typeof entry === "string" ? entry : entry.shortBaseType
  const defaults = LEVELING_AMULETS[shortBaseType]
  return { baseType: defaults.baseType, shortBaseType, entry: defaults.entry }
}

export const normalizeSocketColorPatterns = (patterns: readonly SocketColorPattern[]) => [...new Set(patterns)]
export const normalizeShieldProgressionConfig = (shieldProgression?: ShieldProgressionConfig): NormalizedShieldProgressionConfig => {
  const defaultMode = filterDefaults.shieldProgression.mode
  const earlyMaxAreaLevel = filterDefaults.shieldProgression.earlyMaxAreaLevel
  const mode =
    typeof shieldProgression === "string" || shieldProgression === undefined
      ? (shieldProgression ?? defaultMode)
      : (shieldProgression.mode ?? defaultMode)
  const maxAreaLevel = typeof shieldProgression === "object" ? shieldProgression.maxAreaLevel : undefined
  if (mode === "none") return { enabled: false, maxAreaLevel: maxAreaLevel ?? earlyMaxAreaLevel }
  if (mode === "full") return { enabled: true, maxAreaLevel }
  return { enabled: true, maxAreaLevel: maxAreaLevel ?? earlyMaxAreaLevel }
}
