import type { BaseType, ItemClass, NumberRange, Operator, Rarity } from "../../../types"
import type * as Autogenerated from "../../../types/autogenerated"
import type { SoundFile } from "../../../sounds"
import { filterDefaults } from "../defaults"
import type { DefenceBaseType, WeaponItemClass } from "./item-classes"
import type { WeaponBaseType } from "./weapon-queries"

export type SocketColorPattern = "R" | "G" | "B" | "RG" | "RB" | "GB" | "RGB"
export type TtsFile = string
export type ShieldProgressionMode = "none" | "early" | "full"
export type ShieldProgressionConfig = ShieldProgressionMode | { mode?: ShieldProgressionMode; maxAreaLevel?: number }
export type SharedEarlyWeaponConfig = {
  baseTypes?: readonly WeaponBaseType[]
  itemClasses?: readonly WeaponItemClass[]
  minAps?: number
  maxAreaLevel?: number
}
export type BuildProfile = {
  preferredArmourTypes?: readonly DefenceBaseType[]
  preferredWeaponItemClasses?: readonly WeaponItemClass[]
  preferredWeaponMinAps?: number
  earlyWeapons?: SharedEarlyWeaponConfig
  shieldProgression?: ShieldProgressionConfig
}
export type LinksConfig = {
  twoLinkMaxAreaLevel?: number
  threeLinkMaxAreaLevel?: number
  fourLinkMaxAreaLevel?: number
  prefColors?: readonly SocketColorPattern[]
  genericThreeLinksEnabled?: boolean
  genericFourLinksEnabled?: boolean
  twoLinkSoundId?: NumberRange<1, 17>
  threeLinkSoundId?: NumberRange<1, 17>
}
export type JewelleryConfig = {
  amulets?: readonly LevelingAmuletConfig[]
  amuletMaxAreaLevel?: number
  basicRingMaxAreaLevel?: number
  elementalRingMaxAreaLevel?: number
  beltMaxAreaLevel?: number
}
export type RareItemsConfig = { maxAreaLevel?: number }
export type MagicItemsConfig = { maxAreaLevel?: number }
export type NormalItemsConfig = { maxAreaLevel?: number }
export type TincturesConfig = { baseTypes?: readonly Autogenerated.Tinctures[] }
export type EarlyConfig = { earlyMaxAreaLevel?: number; showRustic?: boolean }
export type ChromaticItemsConfig = { smallMaxAreaLevel?: number; largeMaxAreaLevel?: number }
export type HighlightedBaseTypeConfig = {
  baseTypes?: readonly BaseType[]
  itemClasses?: readonly ItemClass[]
  minAps?: number
  socketColors?: readonly SocketColorPattern[]
  weaponCutoffEnabled?: boolean
  weaponCutoffOverlap?: number
  rarityOperator?: Operator
  rarity?: Rarity
  rarities?: readonly Rarity[]
  minAreaLevel?: number
  maxAreaLevel?: number
  soundId?: NumberRange<1, 17>
  soundFileName?: SoundFile
  tts?: TtsFile
}
export type HighlightedEquipmentConfig = { highlights?: readonly HighlightedBaseTypeConfig[] }
export type BuildSpecificOptions = {
  links?: LinksConfig
  jewellery?: JewelleryConfig
  rareItems?: RareItemsConfig
  magicItems?: MagicItemsConfig
  normalItems?: NormalItemsConfig
  tinctures?: TincturesConfig
  highlightedEquipment?: HighlightedEquipmentConfig
  early?: EarlyConfig
}

export const LEVELING_AMULETS = {
  Amber: { baseType: "Amber Amulet", soundFileName: "amber.mp3" },
  Jade: { baseType: "Jade Amulet", soundFileName: "jade.mp3" },
  Lapis: { baseType: "Lapis Amulet", soundFileName: "lapis.mp3" },
} as const satisfies Record<string, { baseType: Autogenerated.Amulets; soundFileName: SoundFile }>
export type LevelingAmuletShortBaseType = keyof typeof LEVELING_AMULETS
export type LevelingAmuletConfig =
  | LevelingAmuletShortBaseType
  | { shortBaseType: LevelingAmuletShortBaseType; soundFileName?: SoundFile; tts?: TtsFile }
export const normalizeLevelingAmuletConfig = (entry: LevelingAmuletConfig) => {
  const shortBaseType = typeof entry === "string" ? entry : entry.shortBaseType
  const defaults = LEVELING_AMULETS[shortBaseType]
  return {
    baseType: defaults.baseType,
    shortBaseType,
    soundFileName: typeof entry === "string" ? defaults.soundFileName : (entry.soundFileName ?? defaults.soundFileName),
    tts: typeof entry === "string" ? undefined : entry.tts,
  }
}
export const normalizeSocketColorPatterns = (patterns: readonly SocketColorPattern[]) => [...new Set(patterns)]
export const normalizeShieldProgressionConfig = (shieldProgression?: ShieldProgressionConfig) => {
  const defaultMode = filterDefaults.shieldProgression.mode
  const earlyMaxAreaLevel = filterDefaults.shieldProgression.earlyMaxAreaLevel
  const mode =
    typeof shieldProgression === "string" || shieldProgression === undefined
      ? (shieldProgression ?? defaultMode)
      : (shieldProgression.mode ?? defaultMode)
  const maxAreaLevel = typeof shieldProgression === "object" ? shieldProgression.maxAreaLevel : undefined
  if (mode === "none") return { enabled: false, maxAreaLevel: maxAreaLevel ?? earlyMaxAreaLevel }
  if (mode === "full") return { enabled: true, maxAreaLevel }
  return { enabled: true, maxAreaLevel: maxAreaLevel ?? earlyMaxAreaLevel }
}
