import type { BaseType, Color, ItemClass, NumberRange, Operator, Rarity } from "../../../types"
import type * as Autogenerated from "../../../types/autogenerated"
import { MANIFEST_BY_ID, type SoundManifestEntry } from "../../../sounds/manifest"
import { filterDefaults } from "../defaults"
import type { DefenceBaseType, WeaponItemClass } from "./item-classes"
import type { WeaponBaseType } from "./weapon-queries"

export type SocketColorPattern = "R" | "G" | "B" | "RG" | "RB" | "GB" | "RGB"
export type TtsFile = string | SoundManifestEntry
export type ShieldProgressionMode = "none" | "early" | "full"
export type ShieldProgressionConfig = ShieldProgressionMode | { mode?: ShieldProgressionMode; maxAreaLevel?: number }
export type SharedEarlyWeaponConfig = {
  baseTypes?: readonly WeaponBaseType[]
  itemClasses?: readonly WeaponItemClass[]
  minAps?: number
  maxAreaLevel?: number
}
export type BuildProfile = {
  preferredArmourTypes?: readonly DefenceBaseType[]
  preferredWeaponItemClasses?: readonly WeaponItemClass[]
  preferredWeaponMinAps?: number
  earlyWeapons?: SharedEarlyWeaponConfig
  shieldProgression?: ShieldProgressionConfig
}
export type LinksConfig = {
  twoLinkMaxAreaLevel?: number
  threeLinkMaxAreaLevel?: number
  fourLinkMaxAreaLevel?: number
  prefColors?: readonly SocketColorPattern[]
  genericThreeLinksEnabled?: boolean
  genericFourLinksEnabled?: boolean
  twoLinkSoundId?: NumberRange<1, 17>
  threeLinkSoundId?: NumberRange<1, 17>
}
export type JewelleryConfig = {
  amulets?: readonly LevelingAmuletConfig[]
  amuletMaxAreaLevel?: number
  basicRingMaxAreaLevel?: number
  elementalRingMaxAreaLevel?: number
  beltMaxAreaLevel?: number
}
export type RareItemsConfig = { maxAreaLevel?: number }
export type MagicItemsConfig = { maxAreaLevel?: number }
export type NormalItemsConfig = { maxAreaLevel?: number }
export type TincturesConfig = { baseTypes?: readonly Autogenerated.Tinctures[] }
export type EarlyConfig = {
  earlyMaxAreaLevel?: number
  showRustic?: boolean
  includeMomentumColors?: boolean
  momentumColors?: {
    itemClasses?: readonly ItemClass[]
    baseTypes?: readonly BaseType[]
    minAps?: number
    maxAreaLevel?: number
  }
  momentumMaxAreaLevel?: number
}
export type ChromaticItemsConfig = { smallMaxAreaLevel?: number; largeMaxAreaLevel?: number }
export type HighlightedBaseTypeConfig = {
  baseTypes?: readonly BaseType[]
  itemClasses?: readonly ItemClass[]
  minAps?: number
  socketColors?: readonly SocketColorPattern[]
  socketGroups?: readonly string[]
  socketGroupOperator?: Operator
  weaponCutoffEnabled?: boolean
  weaponCutoffOverlap?: number
  rarityOperator?: Operator
  rarity?: Rarity
  rarities?: readonly Rarity[]
  minAreaLevel?: number
  maxAreaLevel?: number
  soundId?: NumberRange<1, 17>
  soundFileName?: string
  tts?: TtsFile
  rarityIconColors?: Partial<Record<"Normal" | "Magic" | "Rare", Color>>
  raritySoundIds?: Partial<Record<"Normal" | "Magic" | "Rare", NumberRange<1, 17>>>
  legacyConditionOrder?: boolean
}
export type HighlightedEquipmentConfig = { highlights?: readonly HighlightedBaseTypeConfig[] }
export type BuildSpecificOptions = {
  links?: LinksConfig
  jewellery?: JewelleryConfig
  rareItems?: RareItemsConfig
  magicItems?: MagicItemsConfig
  normalItems?: NormalItemsConfig
  tinctures?: TincturesConfig
  highlightedEquipment?: HighlightedEquipmentConfig
  early?: EarlyConfig
}

export type NormalizedShieldProgressionConfig = {
  enabled: boolean
  maxAreaLevel?: number
}

export const LEVELING_AMULETS = {
  Amber: { baseType: "Amber Amulet", entry: MANIFEST_BY_ID.amber_amulet },
  Jade: { baseType: "Jade Amulet", entry: MANIFEST_BY_ID.jade_amulet },
  Lapis: { baseType: "Lapis Amulet", entry: MANIFEST_BY_ID.lapis_amulet },
} as const

export type LevelingAmuletShortBaseType = keyof typeof LEVELING_AMULETS
export type LevelingAmuletConfig = LevelingAmuletShortBaseType | { shortBaseType: LevelingAmuletShortBaseType }
export const normalizeLevelingAmuletConfig = (entry: LevelingAmuletConfig) => {
  const shortBaseType = typeof entry === "string" ? entry : entry.shortBaseType
  const defaults = LEVELING_AMULETS[shortBaseType]
  return { baseType: defaults.baseType, shortBaseType, entry: defaults.entry }
}

export const normalizeSocketColorPatterns = (patterns: readonly SocketColorPattern[]) => [...new Set(patterns)]
export const normalizeShieldProgressionConfig = (shieldProgression?: ShieldProgressionConfig): NormalizedShieldProgressionConfig => {
  const defaultMode = filterDefaults.shieldProgression.mode
  const earlyMaxAreaLevel = filterDefaults.shieldProgression.earlyMaxAreaLevel
  const mode =
    typeof shieldProgression === "string" || shieldProgression === undefined
      ? (shieldProgression ?? defaultMode)
      : (shieldProgression.mode ?? defaultMode)
  const maxAreaLevel = typeof shieldProgression === "object" ? shieldProgression.maxAreaLevel : undefined
  if (mode === "none") return { enabled: false, maxAreaLevel: maxAreaLevel ?? earlyMaxAreaLevel }
  if (mode === "full") return { enabled: true, maxAreaLevel }
  return { enabled: true, maxAreaLevel: maxAreaLevel ?? earlyMaxAreaLevel }
}
