import "dotenv/config"
import fs from "fs"
import path from "path"
import { format, resolveConfig } from "prettier"
import { SOUND_PACK_SOURCE_DIR } from "../sounds/paths"

const SOURCE_DIR = `./${SOUND_PACK_SOURCE_DIR}`
const OUTPUT_FILE = "./src/types/sounds/generated-sounds.ts"

async function writeFormattedFile(filePath: string, content: string) {
  const prettierConfig = await resolveConfig(filePath)
  const formattedContent = await format(content, { ...prettierConfig, filepath: filePath })
  fs.writeFileSync(filePath, formattedContent)
}

export async function generateSoundTypes() {
  const files = fs.readdirSync(SOURCE_DIR).sort((left, right) => {
    const caseInsensitiveCompare = left.toLowerCase().localeCompare(right.toLowerCase(), "en")
    return caseInsensitiveCompare !== 0 ? caseInsensitiveCompare : left.localeCompare(right, "en")
  })

  const typeContent = `
// This file is autogenerated by src/scripts/generateSoundTypes.ts
export type SoundFile = 
${files.map((name: string) => `  | '${name}'`).join("\n")}
  `.trim()

  if (!fs.existsSync(path.dirname(OUTPUT_FILE))) {
    fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true })
  }

  await writeFormattedFile(OUTPUT_FILE, typeContent)
}

async function main() {
  await generateSoundTypes()
}

if (require.main === module) {
  void main()
}
