import {
  chromaticItems,
  currency,
  divinationCards,
  early,
  earlySocketFallbacks,
  flasks,
  gems,
  hideEquipment,
  highlightedEquipment,
  jewellery,
  joinSections,
  links,
  misc,
  optionalSection,
  questItems,
  rareItems,
  scrolls,
  showUnknownItems,
  sixSockets,
  socketBases,
  tinctures,
  twilightStrand,
  uniques,
} from "../shared"
import { buildProfile, buildSpecificOptions } from "./config"

export const getFilter = () =>
  joinSections(
    twilightStrand(),
    currency(),
    scrolls(),
    uniques(),
    gems(),
    links({ ...buildProfile, ...buildSpecificOptions.links }),
    sixSockets(),
    optionalSection(buildSpecificOptions.highlightedEquipment, highlightedEquipment),
    optionalSection(buildSpecificOptions.socketBases, (config) => socketBases({ ...buildProfile, ...config })),
    optionalSection(buildSpecificOptions.rareItems, (config) => rareItems({ ...buildProfile, ...config })),
    jewellery(),
    chromaticItems(),
    flasks(),
    optionalSection(buildSpecificOptions.tinctures, tinctures),
    optionalSection(buildSpecificOptions.early, (config) => early({ ...buildProfile, ...config })),
    optionalSection(buildSpecificOptions.earlySocketFallbacks, earlySocketFallbacks),
    questItems(),
    divinationCards(),
    misc(),
    hideEquipment(),
    showUnknownItems(),
  )
