// This file is autogenerated by src/scripts/generateTypes.ts
import {
  ItemClasses,
  StackableCurrency,
  OneHandAxes,
  TwoHandAxes,
  Bows,
  Claws,
  Daggers,
  RuneDaggers,
  OneHandMaces,
  Sceptres,
  TwoHandMaces,
  Staves,
  Warstaves,
  OneHandSwords,
  ThrustingOneHandSwords,
  TwoHandSwords,
  Wands,
  FishingRods,
  BodyArmours,
  Boots,
  Gloves,
  Helmets,
  Shields,
  Amulets,
  Belts,
  Quivers,
  Rings,
  Jewels,
  DivinationCards,
  LifeFlasks,
  ManaFlasks,
  HybridFlasks,
  UtilityFlasks,
  SkillGems,
  SupportGems,
  MapFragments,
  VaultKeys,
  QuestItems,
  LabyrinthItems,
  LabyrinthTrinkets,
  AbyssJewels,
  IncursionItems,
  DelveStackableSocketableCurrency,
  Trinkets,
  HeistTargets,
  Contracts,
  Blueprints,
  HeistCloaks,
  HeistBrooches,
  HeistTools,
  HeistGear,
  MiscMapItems,
  ExpeditionLogbooks,
  AtlasUpgradeItems,
  Maps,
  Relics,
  SanctifiedRelics,
  SanctumResearch,
  Tinctures,
  Charms,
  Corpses,
  Gold,
  Idols,
  Wombgifts,
  Pieces,
  EnshroudedItems,
  Chart,
} from "./autogenerated"

export type BaseType =
  | StackableCurrency
  | OneHandAxes
  | TwoHandAxes
  | Bows
  | Claws
  | Daggers
  | RuneDaggers
  | OneHandMaces
  | Sceptres
  | TwoHandMaces
  | Staves
  | Warstaves
  | OneHandSwords
  | ThrustingOneHandSwords
  | TwoHandSwords
  | Wands
  | FishingRods
  | BodyArmours
  | Boots
  | Gloves
  | Helmets
  | Shields
  | Amulets
  | Belts
  | Quivers
  | Rings
  | Jewels
  | DivinationCards
  | LifeFlasks
  | ManaFlasks
  | HybridFlasks
  | UtilityFlasks
  | SkillGems
  | SupportGems
  | MapFragments
  | VaultKeys
  | QuestItems
  | LabyrinthItems
  | LabyrinthTrinkets
  | AbyssJewels
  | IncursionItems
  | DelveStackableSocketableCurrency
  | Trinkets
  | HeistTargets
  | Contracts
  | Blueprints
  | HeistCloaks
  | HeistBrooches
  | HeistTools
  | HeistGear
  | MiscMapItems
  | ExpeditionLogbooks
  | AtlasUpgradeItems
  | Maps
  | Relics
  | SanctifiedRelics
  | SanctumResearch
  | Tinctures
  | Charms
  | Corpses
  | Gold
  | Idols
  | Wombgifts
  | Pieces
  | EnshroudedItems
  | Chart

export type ItemClass = ItemClasses
