import {
  chromaticItems,
  currency,
  divinationCards,
  early,
  earlySockets,
  flasks,
  gems,
  hideEquipment,
  highlightedEquipment,
  jewellery,
  joinSections,
  links,
  magicItems,
  normalItems,
  misc,
  preferredWeapons,
  questItems,
  rareItems,
  scrolls,
  showUnknownItems,
  sixSockets,
  tinctures,
  twilightStrand,
  uniques,
} from "../shared"
import { buildProfile, buildSpecificOptions } from "./config"

export const getFilter = () =>
  joinSections(
    twilightStrand(),
    currency(),
    scrolls(),
    gems(),
    links({ ...buildProfile, ...(buildSpecificOptions.links ?? {}) }),
    highlightedEquipment(buildSpecificOptions.highlightedEquipment),
    preferredWeapons(buildProfile),
    sixSockets(),
    jewellery(buildSpecificOptions.jewellery),
    early({ ...buildProfile, ...(buildSpecificOptions.early ?? {}) }),
    earlySockets(buildProfile),
    flasks(),
    tinctures(buildSpecificOptions.tinctures),
    chromaticItems(),
    uniques(),
    rareItems({ ...buildProfile, ...(buildSpecificOptions.rareItems ?? {}) }),
    magicItems(buildSpecificOptions.magicItems),
    normalItems(buildSpecificOptions.normalItems),
    questItems(),
    divinationCards(),
    misc(),
    hideEquipment(),
    showUnknownItems(),
  )
